## Wichtige Funktionen aus diesem Kapitel {-}

| Funktion              | Paket        | Beschreibung                     | Wichtige Argumente      |
|-----------------------|--------------|----------------------------------|-------------------------|
| **Grundsätzliches**                                                                               |
| `+`, `-`, `*`,`/`, `^` | base         | einfache Rechenoperationen       |                        |
| `<-`                   | base         | einem Objekt einen Wert zuweisen |                        |
| `$`                    | base         | Über den Namen auf ein Element zugreifen  | z.B. `df$var` |
| `[]`, `[[]]`           | base         | Über den Index auf ein Element zugreifen  | z.B. `[1, 4]` |
| `#`                    | base         | Kommentare schreiben             |                        |
| `?`, `help()`          | base         | Hilfe aufrufen                   |                        |
| `vignette()`           | base         | Vignette aufrufen                |                        |
| `getwd()`              | base         | Arbeitsverzeichnis ausgeben      |                        |           
| `setwd()`              | base         | Arbeitsverzeichnis setzen        |                        |
| **Pakete**                                                                                        |
|`install.packages()`    | base         | Pakete installieren              |                        |
|`library()`             | base         | Pakete laden                     |                        |
| **Funktionen**                                                                                    |
| `function()`           | base         | Funktionen schreiben             |                        |
| **Daten importieren**                                                                             |
| `read_csv2()`          | tidyverse    | Deutsche CSV-Dateien laden       | Pfad, na               |
| `write_csv2()`         | tidyverse    | Deutsche CSV-Dateien speichern   | Datenobjekt, Pfad      |
| `read_csv()`           | tidyverse    | Englische CSV-Dateien laden      | Pfad, na               |
| `write_csv()`          | tidyverse    | Englische CSV-Dateien speichern  | Datenobjekt, Pfad      |
| `read_excel()`         | readxl       | Excel-Dateien laden              | Pfad, na               |
| `read_sav()`           | haven        | SPSS-Dateien laden               | Pfad, na               |
| `write_sav()`          | haven        | SPSS-Dateien speichern           | Datenobjekt, Pfad      |
| **Daten erkunden**                                                                                |
| `head()`               | utils        | Kopf eines Dataframes ausgeben   |                        |
| `names()`              | base         | Namen untergeordneter Objekte    |                        |
| `ncol()`               | base         | Anzahl der Spalten               |                        |
| `nrow()`               | base         | Anzahl der Zeilen                |                        |
| `class()`              | base         | Klasse eines Objekts             |                        |
| `typeof()`             | base         | Typ eines Objekts                |                        |
| **Sonstiges**                                                                                     |
| `c()`                  | base         | Argumente kombinieren            |                        |
| `new_tibble()`         | tidyverse    | Tibble erstellen                 | Liste von Vektoren, n  |
| `factor()`             | base         | Argumente kombinieren            |                        |
| `list()`               | base         | Eine Liste anlegen               |                        |
| `is.na()`              | base         | Prüft, ob ein Wert fehlend ist   |                        |
