## Wichtige Funktionen aus diesem Kapitel {-}

| Funktion           | Paket        | Beschreibung                    | Wichtige Argumente    |
|--------------------|--------------|---------------------------------|-----------------------|
| **Häufigkeiten**                                                                            |
|`table()`           | stats        | einfache Tabelle                | `useNA = "ifany"`     |
|`tabyl()`           | janitor      | Häufigkeitstabelle mit Prozent  |                       |
|`plot_frq()`        | sjPlot       | Säulendiagramm                  |                       |
| **Maße der zentralen Tendenz & Streuung**                                                   |
|`Mode()`            | DescTools    | Modus                           |                       |
|`median()`          | stats        | Median                          | `na.rm = TRUE`        |
|`range()`           | stats        | Range                           | `na.rm = TRUE`        |
|`quantile()`        | stats        | Quantilgrenzen                  | `na.rm = TRUE`        |
|`IQR()`             | stats        | Inter-Quartil-Range             | `na.rm = TRUE`        |
|`mean()`            | base         | Arithmetisches Mittel           | `na.rm = TRUE`        |
|`sd()`              | stats        | Standardabweichung              | `na.rm = TRUE`        |
|`var()`             | stats        | Varianz                         | `na.rm = TRUE`        |
| **Schiefe und Kurtosis**                                                                    |
|`skew()`            | psych        | Schiefe                         | `na.rm = TRUE`        |
|`kurtosi()`         | psych        | Kurtosis                        | `na.rm = TRUE`        |
| **Übersichts-Funktionen**                                                                   |
|`summary()`         | base         | Wichtige Verteilungsmerkmale    |                       |
|`describe()`        | psych        | Tabelle deskriptiver Merkmale   |                       |
