## Wichtige Funktionen aus diesem Kapitel {-}

| Funktion           | Paket        | Beschreibung                    | Wichtige Argumente/Bemerkung |
|--------------------|--------------|---------------------------------|-----------------------|
| **Tabellenanalyse**                                                                         |
|`tabyl()`           | janitor      | Tabellen & Kreuztabellen        | `show_na = FALSE`     |
|`adorn_totals()`    | janitor      | Randhäufigkeiten hinzufügen     | `where = c("row", "col")` |
|`adorn_percentages` | janitor      | In Prozentwerte umwandeln       | `denominator = "col"` |
|`adorn_pct_formatting`| janitor    | Formatierung der Prozentwerte   | `digits = n`          |
|`adorn_ns()`        | janitor      | Absolute Häufigkeiten wieder hinzufügen |               |
|`adorn_titel()`     | janitor      | Variablen in die erste Zelle schreiben  | `placement = "combined"` |
|`chisq.test()`      | janitor      | Chi-Quadrat-Test                | einfache Kreuztabelle |
|`CramerV()`         | DescTools    | Cramer´s V                      | Kreuztabelle ohne erste Spalte! |
| **Kovarianz & Korrelation**                                                   |
|`cov()`             | stats        | Kovarianz                       |                       |
|`cor()`             | stats        | Korrelation                     |                       |
|`cor.test()`        | stats        | Signifikanztest für r           | `use`, `alternative`  |
|`corr.test()`       | psych        | Korrelation + Signifikanztest   | `use`, `method`       |
|`partial.r()`       | psych        | Partialkorrelation              |                       |
|`corr.p()`          | psych        | Signifikanztest für Partialkorrelation   | `n`                   |
|`correlate()`       | corrr        | Korrelationsmatrix              |                       |
| **Grafiken**                                                                                |
|`ggplot()`          | ggplot2      | Plot anlegen                    | `aes()`               |
|`geom_jitter()`     | ggplot2      | "zitternder" Scatterplot        |                       |
|`aes()`             | ggplot2      | "Ästhetik" des Plots            | Variablen, die im Plot darzustellen sind |
|`rplot()`           | corrr        | Korrelations-Plot               |                       |
