<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Kapitel 5 Datenaufbereitung | r_book.utf8</title>
  <meta name="description" content="Dieses Buch ist als Nachschlage-Referez für die Statistik-Ausbildung in der Kommunikationswissenschaft gedacht." />
  <meta name="generator" content="bookdown 0.19 and GitBook 2.6.7" />

  <meta property="og:title" content="Kapitel 5 Datenaufbereitung | r_book.utf8" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Dieses Buch ist als Nachschlage-Referez für die Statistik-Ausbildung in der Kommunikationswissenschaft gedacht." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Kapitel 5 Datenaufbereitung | r_book.utf8" />
  
  <meta name="twitter:description" content="Dieses Buch ist als Nachschlage-Referez für die Statistik-Ausbildung in der Kommunikationswissenschaft gedacht." />
  

<meta name="author" content="Julia Niemann-Lenz" />


<meta name="date" content="2020-12-02" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="einführung-in-r-1.html"/>
<link rel="next" href="deskriptive-statistik.html"/>
<script src="libs/header-attrs-2.4.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-HCCP0H824J"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-HCCP0H824J');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R Kompendium</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Herzlich Willkommen!</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#dank"><i class="fa fa-check"></i>Dank</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#disclaimer"><i class="fa fa-check"></i>Disclaimer</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Einleitung</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#einführung-in-r"><i class="fa fa-check"></i><b>1.1</b> Einführung in R</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="intro.html"><a href="intro.html#s-ist-die-mutter-von-r"><i class="fa fa-check"></i><b>1.1.1</b> S ist die Mutter von R</a></li>
<li class="chapter" data-level="1.1.2" data-path="intro.html"><a href="intro.html#die-philosophie-von-s"><i class="fa fa-check"></i><b>1.1.2</b> Die Philosophie von S</a></li>
<li class="chapter" data-level="1.1.3" data-path="intro.html"><a href="intro.html#die-entwicklung-von-r"><i class="fa fa-check"></i><b>1.1.3</b> Die Entwicklung von R</a></li>
<li class="chapter" data-level="" data-path="intro.html"><a href="intro.html#weiterführende-links"><i class="fa fa-check"></i>Weiterführende Links</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#vorteile-von-r"><i class="fa fa-check"></i><b>1.2</b> Vorteile von R</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#alternativen-zu-r"><i class="fa fa-check"></i><b>1.3</b> Alternativen zu R</a>
<ul>
<li class="chapter" data-level="" data-path="intro.html"><a href="intro.html#weiterführende-links-1"><i class="fa fa-check"></i>Weiterführende Links</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#tipps-zum-r-lernen"><i class="fa fa-check"></i><b>1.4</b> Tipps zum R lernen</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="intro.html"><a href="intro.html#der-anfang-ist-schwer"><i class="fa fa-check"></i><b>1.4.1</b> Der Anfang ist schwer</a></li>
<li class="chapter" data-level="1.4.2" data-path="intro.html"><a href="intro.html#nützliche-hinweise"><i class="fa fa-check"></i><b>1.4.2</b> Nützliche Hinweise</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="benutzeroberflächen.html"><a href="benutzeroberflächen.html"><i class="fa fa-check"></i><b>2</b> Benutzeroberflächen</a>
<ul>
<li class="chapter" data-level="2.1" data-path="benutzeroberflächen.html"><a href="benutzeroberflächen.html#konsole"><i class="fa fa-check"></i><b>2.1</b> R Konsole</a></li>
<li class="chapter" data-level="2.2" data-path="benutzeroberflächen.html"><a href="benutzeroberflächen.html#rstudio-ide-für-r"><i class="fa fa-check"></i><b>2.2</b> RStudio: IDE für R</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="benutzeroberflächen.html"><a href="benutzeroberflächen.html#rstudio-cloud"><i class="fa fa-check"></i><b>2.2.1</b> RStudio-Cloud</a></li>
<li class="chapter" data-level="2.2.2" data-path="benutzeroberflächen.html"><a href="benutzeroberflächen.html#installation-von-rstudio"><i class="fa fa-check"></i><b>2.2.2</b> Installation von RStudio</a></li>
<li class="chapter" data-level="2.2.3" data-path="benutzeroberflächen.html"><a href="benutzeroberflächen.html#rstudio-benutzeroberfläche"><i class="fa fa-check"></i><b>2.2.3</b> RStudio Benutzeroberfläche</a></li>
<li class="chapter" data-level="2.2.4" data-path="benutzeroberflächen.html"><a href="benutzeroberflächen.html#r-skripte"><i class="fa fa-check"></i><b>2.2.4</b> R-Skripte</a></li>
<li class="chapter" data-level="2.2.5" data-path="benutzeroberflächen.html"><a href="benutzeroberflächen.html#features-von-rstudio"><i class="fa fa-check"></i><b>2.2.5</b> Features von RStudio</a></li>
<li class="chapter" data-level="2.2.6" data-path="benutzeroberflächen.html"><a href="benutzeroberflächen.html#rstudio-anpassen"><i class="fa fa-check"></i><b>2.2.6</b> RStudio anpassen</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="installation.html"><a href="installation.html"><i class="fa fa-check"></i><b>3</b> Installation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="installation.html"><a href="installation.html#installationsanleitung-windows"><i class="fa fa-check"></i><b>3.1</b> Installationsanleitung Windows</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="installation.html"><a href="installation.html#erster-schritt-r"><i class="fa fa-check"></i><b>3.1.1</b> Erster Schritt: R</a></li>
<li class="chapter" data-level="3.1.2" data-path="installation.html"><a href="installation.html#zweiter-schritt-rstudio"><i class="fa fa-check"></i><b>3.1.2</b> Zweiter Schritt: RStudio</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="installation.html"><a href="installation.html#installationsanleitung-macos"><i class="fa fa-check"></i><b>3.2</b> Installationsanleitung MacOS</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="installation.html"><a href="installation.html#erster-schritt-r-1"><i class="fa fa-check"></i><b>3.2.1</b> Erster Schritt: R</a></li>
<li class="chapter" data-level="3.2.2" data-path="installation.html"><a href="installation.html#zweiter-schritt-rstudio-1"><i class="fa fa-check"></i><b>3.2.2</b> Zweiter Schritt: RStudio</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html"><i class="fa fa-check"></i><b>4</b> Einführung in R</a>
<ul>
<li class="chapter" data-level="4.1" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#r-syntax"><i class="fa fa-check"></i><b>4.1</b> R-Syntax</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#rechnen-mit-r"><i class="fa fa-check"></i><b>4.1.1</b> Rechnen mit R</a></li>
<li class="chapter" data-level="4.1.2" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#zuweisungsoperator"><i class="fa fa-check"></i><b>4.1.2</b> Zuweisungsoperator</a></li>
<li class="chapter" data-level="4.1.3" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#objektnamen"><i class="fa fa-check"></i><b>4.1.3</b> Objektnamen</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#kommentare"><i class="fa fa-check"></i><b>4.2</b> Kommentare</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#einfache-kommentare"><i class="fa fa-check"></i><b>4.2.1</b> Einfache Kommentare</a></li>
<li class="chapter" data-level="4.2.2" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#sections"><i class="fa fa-check"></i><b>4.2.2</b> Sections</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#r-pakete"><i class="fa fa-check"></i><b>4.3</b> R-Pakete</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#r-pakete-anzeigen"><i class="fa fa-check"></i><b>4.3.1</b> R-Pakete anzeigen</a></li>
<li class="chapter" data-level="4.3.2" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#r-pakete-installieren"><i class="fa fa-check"></i><b>4.3.2</b> R-Pakete installieren</a></li>
<li class="chapter" data-level="4.3.3" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#pakete-laden"><i class="fa fa-check"></i><b>4.3.3</b> Pakete laden</a></li>
<li class="chapter" data-level="4.3.4" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#dokumentation"><i class="fa fa-check"></i><b>4.3.4</b> Dokumentation</a></li>
<li class="chapter" data-level="4.3.5" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#pakete-finden"><i class="fa fa-check"></i><b>4.3.5</b> Pakete finden</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#funktionen"><i class="fa fa-check"></i><b>4.4</b> Funktionen</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#aufbau-argumente"><i class="fa fa-check"></i><b>4.4.1</b> Aufbau &amp; Argumente</a></li>
<li class="chapter" data-level="4.4.2" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#funktionen-verschachteln"><i class="fa fa-check"></i><b>4.4.2</b> Funktionen verschachteln</a></li>
<li class="chapter" data-level="4.4.3" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#hilfe-für-funktionen"><i class="fa fa-check"></i><b>4.4.3</b> Hilfe für Funktionen</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#doppelte-funktionsnamen"><i class="fa fa-check"></i><b>4.5</b> Doppelte Funktionsnamen</a></li>
<li class="chapter" data-level="4.6" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#eigene-funktionen-schreiben"><i class="fa fa-check"></i><b>4.6</b> Eigene Funktionen schreiben</a></li>
<li class="chapter" data-level="4.7" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#r-projekte"><i class="fa fa-check"></i><b>4.7</b> R-Projekte</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#arbeitsverzeichnis"><i class="fa fa-check"></i><b>4.7.1</b> Arbeitsverzeichnis</a></li>
<li class="chapter" data-level="4.7.2" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#r-projekte-anlegen"><i class="fa fa-check"></i><b>4.7.2</b> R-Projekte anlegen</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#daten-im--und--export"><i class="fa fa-check"></i><b>4.8</b> Daten-Im- und -Export</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#csv-dateien-importieren"><i class="fa fa-check"></i><b>4.8.1</b> CSV-Dateien importieren</a></li>
<li class="chapter" data-level="4.8.2" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#excel-dateien-importieren"><i class="fa fa-check"></i><b>4.8.2</b> Excel-Dateien importieren</a></li>
<li class="chapter" data-level="4.8.3" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#spss-dateien-importieren"><i class="fa fa-check"></i><b>4.8.3</b> SPSS-Dateien importieren</a></li>
<li class="chapter" data-level="4.8.4" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#daten-exportieren-abspeichern"><i class="fa fa-check"></i><b>4.8.4</b> Daten exportieren (abspeichern)</a></li>
<li class="chapter" data-level="4.8.5" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#work_labelled"><i class="fa fa-check"></i><b>4.8.5</b> Arbeit mit gelabelten Daten</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#datenstrukturen"><i class="fa fa-check"></i><b>4.9</b> Datenstrukturen</a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#dataframes"><i class="fa fa-check"></i><b>4.9.1</b> Dataframes</a></li>
<li class="chapter" data-level="4.9.2" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#aufbau-von-dataframes"><i class="fa fa-check"></i><b>4.9.2</b> Aufbau von Dataframes</a></li>
<li class="chapter" data-level="4.9.3" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#atomic_vector_types"><i class="fa fa-check"></i><b>4.9.3</b> Atomare Datentypen</a></li>
<li class="chapter" data-level="4.9.4" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#fehlende-werte"><i class="fa fa-check"></i><b>4.9.4</b> Fehlende Werte</a></li>
<li class="chapter" data-level="4.9.5" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#objekttypen-konvertieren"><i class="fa fa-check"></i><b>4.9.5</b> Objekttypen konvertieren</a></li>
<li class="chapter" data-level="4.9.6" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#faktoren"><i class="fa fa-check"></i><b>4.9.6</b> Faktoren</a></li>
<li class="chapter" data-level="4.9.7" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#listen"><i class="fa fa-check"></i><b>4.9.7</b> Listen</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#wichtige-funktionen-aus-diesem-kapitel"><i class="fa fa-check"></i>Wichtige Funktionen aus diesem Kapitel</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html"><i class="fa fa-check"></i><b>5</b> Datenaufbereitung</a>
<ul>
<li class="chapter" data-level="5.1" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#datensatz-für-dieses-kapitel"><i class="fa fa-check"></i><b>5.1</b> Datensatz für dieses Kapitel</a></li>
<li class="chapter" data-level="5.2" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#pipe"><i class="fa fa-check"></i><b>5.2</b> Die Pipe</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#der-aufbau-im-detail"><i class="fa fa-check"></i><b>5.2.1</b> Der Aufbau im Detail</a></li>
<li class="chapter" data-level="5.2.2" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#schlechtere-alternativen-zur-pipe"><i class="fa fa-check"></i><b>5.2.2</b> Schlechtere Alternativen zur Pipe</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#filter-fälle-auswählen"><i class="fa fa-check"></i><b>5.3</b> Filter: Fälle auswählen</a></li>
<li class="chapter" data-level="5.4" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#arrange-fälle-sortieren"><i class="fa fa-check"></i><b>5.4</b> Arrange: Fälle sortieren</a></li>
<li class="chapter" data-level="5.5" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#select-variablen-auswählen"><i class="fa fa-check"></i><b>5.5</b> Select: Variablen auswählen</a></li>
<li class="chapter" data-level="5.6" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#variablen-umcodieren"><i class="fa fa-check"></i><b>5.6</b> Variablen umcodieren</a></li>
<li class="chapter" data-level="5.7" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#mutate-variablen-berechnen"><i class="fa fa-check"></i><b>5.7</b> Mutate: Variablen berechnen</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#variablen-unter-einer-bedingung-berechnen"><i class="fa fa-check"></i><b>5.7.1</b> Variablen unter einer Bedingung berechnen</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#summary-daten-verdichten"><i class="fa fa-check"></i><b>5.8</b> Summary: Daten verdichten</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html"><i class="fa fa-check"></i><b>6</b> Deskriptive Statistik</a>
<ul>
<li class="chapter" data-level="6.1" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#datensatz-für-dieses-kapitel-1"><i class="fa fa-check"></i><b>6.1</b> Datensatz für dieses Kapitel</a></li>
<li class="chapter" data-level="6.2" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#häufigkeitsverteilung"><i class="fa fa-check"></i><b>6.2</b> Häufigkeitsverteilung</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#tabellen"><i class="fa fa-check"></i><b>6.2.1</b> Tabellen</a></li>
<li class="chapter" data-level="6.2.2" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#häufigkeitsdiagramm"><i class="fa fa-check"></i><b>6.2.2</b> Häufigkeitsdiagramm</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#maße-der-zentralen-tendenz-streuung"><i class="fa fa-check"></i><b>6.3</b> Maße der zentralen Tendenz &amp; Streuung</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#nominale-daten"><i class="fa fa-check"></i><b>6.3.1</b> Nominale Daten</a></li>
<li class="chapter" data-level="6.3.2" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#ordinale-daten"><i class="fa fa-check"></i><b>6.3.2</b> Ordinale Daten</a></li>
<li class="chapter" data-level="6.3.3" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#metrische-daten"><i class="fa fa-check"></i><b>6.3.3</b> Metrische Daten</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#schiefe-und-kurtosis"><i class="fa fa-check"></i><b>6.4</b> Schiefe und Kurtosis</a></li>
<li class="chapter" data-level="6.5" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#übersichts-funktionen"><i class="fa fa-check"></i><b>6.5</b> Übersichts-Funktionen</a></li>
<li class="chapter" data-level="" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#wichtige-funktionen-aus-diesem-kapitel-1"><i class="fa fa-check"></i>Wichtige Funktionen aus diesem Kapitel</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="literaturverzeichnis.html"><a href="literaturverzeichnis.html"><i class="fa fa-check"></i>Literaturverzeichnis</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="datenaufbereitung" class="section level1" number="5">
<h1><span class="header-section-number">Kapitel 5</span> Datenaufbereitung</h1>
<p>Datenaufbereitung (<em>data wrangling</em>) bezeichnet den Prozess, in dem Rohdaten so verändert, sortiert, umstrukturiert und ausgewählt werden, dass man sie für die anvisierte Analyse verwenden kann.</p>
<p>Im einzelnen werden in diesem Kapitel die folgenden Funktionen erklärt:</p>
<ul>
<li><p><code>filter()</code> zur Auswahl von Fällen</p></li>
<li><p><code>arrange()</code> zur Sortierung von Fällen</p></li>
<li><p><code>rec()</code> zum Umcodieren von Variablen</p></li>
<li><p><code>mutate()</code> zum Anlegen und Berechnen neuer Variablen</p></li>
<li><p><code>select()</code> zur Auswahl von Variablen</p></li>
<li><p><code>summarize()</code> um Daten zu verdichten</p></li>
</ul>
<p>Die letzte Funktion entfaltet besondere Stärken im Zusammenhang mit <code>group_by()</code>. Dadurch kann man Auswertungen oder bestimmte Datentransformationen nach Gruppen aufteilen.</p>
<p>Fast alle der hier vorgestellten Funktionen gehören zum Paket <code>dplyr</code> aus dem Tidyverse. Die einzige Ausnahme bildet <code>rec()</code> aus dem Paket <code>sjmisc</code>. Obwohl sie aus unterschiedlichen Paketen stammen folgen alle dem Tidyverse-Konzept und funktionieren auf ähnliche Weise <span class="citation">(vgl. <a href="literaturverzeichnis.html#ref-Wickham_2017" role="doc-biblioref">Wickham and Grolemund 2017</a>, Kap. 5.1.3)</span>:</p>
<ul>
<li><p>Das erste Argument ist immer der Dataframe.</p></li>
<li><p>Die folgenden Argumente beschreiben, wie der Dataframe umgeformt werden soll (ohne Anführungsstriche).</p></li>
<li><p>Soll innerhalb der Funktionen auf Variablen aus dem Dataframe zugegriffen werden, kann man diese direkt ansprechen (also einfach nur <code>var_name</code> und <strong>nicht</strong> <code>data$var_name</code> oder <code>"var_name"</code>).</p></li>
<li><p>Das Ergebnis ist immer ein Dataframe.</p></li>
</ul>
<div id="datensatz-für-dieses-kapitel" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> Datensatz für dieses Kapitel</h2>
<p>Als Datensatz dient in diesem Kapitel der “starwars”-Datensatz, der im Paket dplyr enthalten ist. Er enthält verschiedene Merkmale von Starwars-Figuren:</p>
<pre><code>## # A tibble: 87 x 14
##    name  height  mass hair_color skin_color eye_color birth_year sex   gender
##    &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
##  1 Luke…    172    77 blond      fair       blue            19   male  mascu…
##  2 C-3PO    167    75 &lt;NA&gt;       gold       yellow         112   none  mascu…
##  3 R2-D2     96    32 &lt;NA&gt;       white, bl… red             33   none  mascu…
##  4 Dart…    202   136 none       white      yellow          41.9 male  mascu…
##  5 Leia…    150    49 brown      light      brown           19   fema… femin…
##  6 Owen…    178   120 brown, gr… light      blue            52   male  mascu…
##  7 Beru…    165    75 brown      light      blue            47   fema… femin…
##  8 R5-D4     97    32 &lt;NA&gt;       white, red red             NA   none  mascu…
##  9 Bigg…    183    84 black      light      brown           24   male  mascu…
## 10 Obi-…    182    77 auburn, w… fair       blue-gray       57   male  mascu…
## # … with 77 more rows, and 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;,
## #   films &lt;list&gt;, vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
</div>
<div id="pipe" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Die Pipe</h2>
<p><img src="images/hex_pipe.png" alt="Hexsticker pipe"  style="float:right;margin-top:15;margin-left:15px;margin-bottom:5px">Bevor es mit den einzelnen Schritten der Datenaufbereitung losgeht, wird an dieser Stelle noch ein neuer Operator eingeführt, die <em>Pipe</em>. In R geschrieben durch die Zeichenfolge <code>%&gt;%</code>. Eine Pipe kann man auch durch den Shortcut <code>Ctrl/Strg + Shift + m</code> einfügen. Merken Sie sich diesen Shortcut gut. Sie werden ihn oft brauchen!</p>
<p>Die Pipe macht etwas, das für Sie zunächst tendenziell unsinnig klingen muss: Sie leitet das Ergebnis einer Funktion als Argument an die nächste Funktion weiter. Gerade bei der Datenaufbereitung ist das jedoch sehr praktisch, weil man häufig mehrere Funktionen hintereinanderschalten muss: Man möcht z.B. zunächst ein paar Fälle herausfiltern, dann eine neue Variable bilden, alte Variablen löschen, andere Variablen umcodieren, dann Variablen auswählen, den Datensatz neu sortieren und schließlich nochmal ein paar Fälle herausfilten und zum Schluss eine Analyse machen. Zusammengefasst: Es sollen sehr viele Transformationen eines Datensatzes hintereinander geschaltet werden.</p>
<div id="der-aufbau-im-detail" class="section level3" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Der Aufbau im Detail</h3>
<p>Hier der schematische Aufbau einer Datentransformation mit Pipe, damit Sie nachvollziehen können, wie der Pipe-Operator funktioniert:</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="datenaufbereitung.html#cb96-1" aria-hidden="true" tabindex="-1"></a>new_data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb96-2"><a href="datenaufbereitung.html#cb96-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transformation_1</span>(<span class="st">&quot;do something&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb96-3"><a href="datenaufbereitung.html#cb96-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transformation_2</span>(<span class="st">&quot;do something else&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb96-4"><a href="datenaufbereitung.html#cb96-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transformation_3</span>(<span class="st">&quot;do something else else&quot;</span>) </span></code></pre></div>
<p>Schauen wir uns mal zeilenweise an, was hier passiert:</p>
<ol style="list-style-type: decimal">
<li><p>Erste Zeile: Der Start</p>
<ul>
<li><p>Zunächst wird ein neues Objekt <code>new_data</code> erzeugt, indem das alte Objekt <code>data</code> - also unser Datensatz - kopiert wird. Dieser Schritt ist immer dann nötig, wenn man mit dem Datensatz weiterarbeiten möchte.</p></li>
<li><p>Nachdem die Operation durchgeführt wurde, wird das Ergebnis dieser Operation (also das neue Objekt <code>new_data</code>) mit der Pipe <code>%&gt;%</code> an die nächste Zeile übergeben.</p></li>
</ul></li>
<li><p>Zweite Zeile: Wo landet das Objekt <code>new_data</code>? Ich habe eben geschrieben, dass das Objekt an die nächste Zeile übergeben wurde. Es ist vielleicht etwas irritierend, das es gar nicht mehr zu sehen ist. Also wo ist es?</p>
<ul>
<li><p>Es steckt in der Funktion dieser Zeile, also im <code>transformation_1()</code> und zwar als erstes Argument. Durch die Pipe ist es quasi unsichtbar. Gedanklich kann man sich den Befehl in dieser Zeile so vorstellen: <code>transformation_1(new_data, "do something")</code> - nur, dass man <code>new_data</code> dort nicht extra erwähnen muss, weil durch die Pipe in der vorhergehenden Zeile klar ist, dass dieses Objet das erste Argument ist.</p></li>
<li><p>Die Funktion <code>transformation_1</code> wird also mit den beiden Argumenten <code>new_data</code> und <code>"do something"</code> ausgeführt. Der Datensatz verändert sich entsprechend. Er behält aber den gleichen Namen.</p></li>
<li><p>Am Ende der Zeile steht wieder eine Pipe <code>%&gt;%</code>. Auch sie leitet das Ergebnis der vorhergehenden Transformation an die nächste Zeile weiter.</p></li>
</ul></li>
<li><p>Dritte Zeile: …same procedere as every pipe…</p>
<ul>
<li><p>Wieder landet der (nun einmal transformierte) Dataframe <code>new_data</code> als erstes Argument in einer Funktion, diesmal in <code>transformation_2()</code>.</p></li>
<li><p>Wieder wird der Dataframe irgendwie transformiert und heiß noch immer gleich.</p></li>
<li><p>Wieder wird er durch die Pipe am Ende der Zeile an die nächste Zeile übergeben.</p></li>
</ul></li>
<li><p>Vierte Zeile: Das Ende naht.</p>
<ul>
<li><p>Auch hier wieder das selbe Spiel wie zuvor: Der Datensatz landet als erstes Argument in der Funktion <code>transformation_3()</code>, die irgendwelche Operationen mit ihm durchführt.</p></li>
<li><p>Nach der Transformation ist allerdings Schluss, denn da ist keine weitere Pipe. Der nun dreifach transformierte Datensatz ist jetzt fertig und liegt als neues Objekt <code>new_data</code> vor. Sie finden es im Environment-Tab.</p></li>
</ul></li>
</ol>
<p>Insgesamt ist die Pipe-Schreibweise sehr übersichtlich, weil die einzelnen Transformationen schön untereinander aufgeführt werden. Man kann also sehr schnell erkennen, was mit dem Dataframe passiert.</p>
<p>Noch eine kleine Anmerkung zur ersten Zeile: Dort habe ich durch <code>new_data &lt;- data</code> ein neues Objekt erzeugt. Das ist immer dann sinnvoll, wenn man nach der Transformation die Daten als Objekt vorliegen haben möchte, um damit z.B. verschiedene statistische Berechnungen durchzuführen. Manchmal benötigt man aber gar kein neues Objekt. Vielleicht möchte man nur temporär etwas ausgeben. In diesem Fall könnte man auch direkt mit <code>data %&gt;%</code> starten. In diesem Kapitel werde ich beides benutzen, da es mir hier auch nicht immer darum geht, den Datensatz tatsächlich zu transformieren.</p>
</div>
<div id="schlechtere-alternativen-zur-pipe" class="section level3" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> Schlechtere Alternativen zur Pipe</h3>
<p>Schauen wir uns einmal an, was die Alternativen zur Arbeit mit der Pipe wären. Es gibt 3:</p>
<ul>
<li><p>Selbstverständlich könnte man alle Datentransformationen nacheinander machen und dabei den Dataframe, den es zu bearbeiten gilt, immer wieder überschreiben. Das ist jedoch keine saubere Arbeitsweise, es ist sehr anfällig für Fehler.</p></li>
<li><p>Eine andere Option wäre es, jedes Mal ein neues Objekt zu erzeugen und die Objekte dann durchzunummerieren oder zu benennen (<code>data_1</code>, <code>data_2</code>, <code>data_3</code> oder <code>data_filtered</code>, <code>data_sorted</code>, <code>data_with_var_x</code>). Auch nicht sehr übersichtlich und ebenfalls fehleranfällig.</p></li>
<li><p>Die dritte Möglichkeit wäre es, Funktionen ineinander zu verschachteln, etwa so: <code>fun1(fun2(fun3(arg1, arg2)), arg1, arg2)</code>. R würde diese dann von innen nach außen abarbeiten. Das ist zwar sehr kompakt, allerdings ist es sehr schwer hier den Überblick zu behalten und auch hier sind Fehler (etwa bei der Klammersetzung) vorprogrammiert.</p></li>
</ul>
<p>Besser sie gewöhnen sich die Arbeit mit der Pipe direkt an. Gerade für den Bereich Datenaufbereitung macht die Pipe sehr viel Sinn, weil in den Funktionen das Datenargument immer an der ersten Stelle steht. Das kommt der Pipe sehr entgegen, weil man den Dataframe so quasi von oben nach unten durch die Pipe leiten und in jedem Schritt ein bisschen weiter umformen kann. Auch wenn die Pipes in diesem Kapitel noch nicht besonders lang sein werden verwende ich diese Schreibweise, einfach, damit Sie sich daran gewöhnen.</p>
</div>
</div>
<div id="filter-fälle-auswählen" class="section level2" number="5.3">
<h2><span class="header-section-number">5.3</span> Filter: Fälle auswählen</h2>
<p>Mit Filtern kann man die Fallzahl eines Datensatzes nach bestimmten Kriterien verringern, also Fälle herausfiltert, die man nicht benötigt bzw. momentan nicht berücksichtigen möchte.</p>
<ul>
<li><p>Fälle entfernen, die man grundsätzlich nicht im Datensatz haben wollte, z.B. Minderjährige, wenn man nur Erwachsene befragen wollte.</p></li>
<li><p>Dubletten entfernen (falls aus Versehen ein Fall doppelt eingegeben wurde)</p></li>
<li><p>Einen Datensatz für eine bestimmte Analyse erstellen, die sich nur auf eine Teilstichprobe bezieht:</p>
<ul>
<li><p>alle Folgen von Serien die länger als 60 Minuten sind</p></li>
<li><p>nur nicht-männliche Befragte</p></li>
<li><p>alle Personen die YouTube oder Instagram regelmäßig nutzen</p></li>
</ul></li>
</ul>
<img src="images/ah_dplyr_filter.jpg" alt="Artwork by Allison Horst" style="width:1000px;margin-bottom:5px;margin-top:50px">
<div style="color:grey;text-align:right">
Artwork by <a href="https://github.com/allisonhorst/stats-illustrations/">Allison Horst</a>
</div>
<p><br /></p>
<p>Im folgenden Beispiel möchte ich einen Datensatz erstellen, der nur Fälle von Personen enthält, die angegeben haben aus dem Bundesland Niedersachsen (Code 3) zu kommen. Bevor man einen Filter anwendet, sollte man sich aber zunächst einen Überblick über die Ausgangslage verschaffen. Ich lasse mir deshalb einmal die Anzahl der Zeilen im Datensatz ausgeben und schaue mir die ersten paar Fälle an:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="datenaufbereitung.html#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(data)</span></code></pre></div>
<pre><code>## [1] 1006</code></pre>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="datenaufbereitung.html#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code></pre></div>
<pre><code>##   lfdn alter geschlecht bundesland verbundenheit_dtl verbundenheit_europa
## 1 1634    23          1          7                 2                    2
## 2 1636    24          2          6                 2                    3
## 3 1637    23          1          3                 2                    2
## 4 1638    23          2          1                 2                    3
## 5 1639    24          1          7                 3                    3
## 6 1640    24          2          8                 4                    4</code></pre>
<p>Okay, der ursprüngliche Datensatz hat 1006 Zeilen (Befragte) und bei den Bundesländern gibt es gemischte Werte (z.B. 1, 3, 6 usw.).</p>
<p>Als nächstes muss eine Filterbedingung festgelegt werden. Die Filterbedingung ist nach den Daten das zweite und zwingende Argument, dass die <code>filter()</code>-Funktion benötigt. Hier kommt der Datentyp “logical” ins Spiel, den wir <a href="einführung-in-r-1.html#atomic_vector_types">hier</a> besprochen haben. Anhand der Filterbedingung prüft die Funktion <code>filter()</code> für jeden Fall im Datensatz, ob eine zuvor von uns definierte Bedingung <code>TRUE</code> oder <code>FALSE</code> ist. Ist das Ergebnis der Prüfung <code>TRUE</code> verbleibt der Fall im Datensatz. Ist es <code>FALSE</code> wird der Fall aus dem Datensatz entfernt. Die Prüfung erfolgt anhand der relationalen Operatoren (z.B. <code>==</code> für “ist gleich,” <code>!=</code> für “ist ungleich” oder <code>&lt;</code> für “ist kleiner als”).</p>
<p>Im Beispiel wollen wir alle Niedersachsen in einem Datensatz abspeichern. Wir müssen also die Bedingung “Das Bundesland ist gleich Niedersachsen” so formulieren, dass R sie versteht. Wir wissen bereits, dass Niedersachsen den Code 3 hat also ist die Filterbedingung: <code>bundesland == 3</code>. Man braucht hier zwingend doppelte Gleichzeichen. Dies ist nötig, weil das einfache Gleichzeichen von R als Zuweisungsoperator <code>&lt;-</code> verstanden würde. Hier soll aber nichts zugewiesen sondern lediglich etwas verglichen werden.</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="datenaufbereitung.html#cb101-1" aria-hidden="true" tabindex="-1"></a>data_nds <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb101-2"><a href="datenaufbereitung.html#cb101-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(bundesland <span class="sc">==</span> <span class="dv">3</span>)</span></code></pre></div>
<p>Gar nicht so schwer, aber hat das auch funktioniert? Schauen wir uns nochmal die Fallzahl und den Datensatz genauer an:</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="datenaufbereitung.html#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(data_nds)</span></code></pre></div>
<pre><code>## [1] 107</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="datenaufbereitung.html#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data_nds)</span></code></pre></div>
<pre><code>##   lfdn alter geschlecht bundesland verbundenheit_dtl verbundenheit_europa
## 1 1637    23          1          3                 2                    2
## 2 1641    23          2          3                 3                    3
## 3 1657    14          2          3                 2                    2
## 4 1680    15          1          3                 1                   99
## 5 1692    17          2          3                 2                    3
## 6 1717    15          2          3                 3                    3</code></pre>
<p>Tatsächlich! Im Datensatz sind jetzt nur noch n = 107 Fälle und in der Variable <code>bundesland</code> haben alle Fälle den Wert 3.</p>
<p>Jetzt machen wir es komplizierter. Wir möchten jetzt alle Personen haben die aus Niedersachsen oder Hamburg kommen und jünger als 18 Jahre sind. Um eine so komplexe Bedingung zu formulieren braucht man neben den relationalen Operatoren auch noch logische Operatoren und Klammer-Regeln.</p>
<p>Mit logischen Operatoren kann man Bedingungen verknüpfen oder gegenseitig ausschließen. Die Wichtigsten sind:</p>
<ul>
<li><p><code>&amp;</code> für “und”</p></li>
<li><p><code>|</code> für “oder”</p></li>
<li><p><code>!</code> für “nicht”</p></li>
</ul>
<p>Die Bedingung “aus Niedersachsen oder Hamburg und jünger als 18 Jahre” lässt sich also wie folgt formulieren: <code>(bundesland = 3 | bundesland = 2) &amp; alter &lt; 18</code>. Hier kommt es haargeanau auf die Klammern an. Wären sie nicht gesetzt würde R möglicherweise alle Niedersachen (egal welchen Alters) und alle Hamburger unter 18 in den Dataframe packen.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="datenaufbereitung.html#cb106-1" aria-hidden="true" tabindex="-1"></a>data_filter <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb106-2"><a href="datenaufbereitung.html#cb106-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>((bundesland <span class="sc">==</span> <span class="dv">3</span> <span class="sc">|</span> bundesland <span class="sc">==</span> <span class="dv">2</span>) <span class="sc">&amp;</span> alter <span class="sc">&lt;</span> <span class="dv">18</span>)</span>
<span id="cb106-3"><a href="datenaufbereitung.html#cb106-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-4"><a href="datenaufbereitung.html#cb106-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(data_filter)</span></code></pre></div>
<pre><code>## [1] 49</code></pre>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="datenaufbereitung.html#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data_filter)</span></code></pre></div>
<pre><code>##   lfdn alter geschlecht bundesland verbundenheit_dtl verbundenheit_europa
## 1 1657    14          2          3                 2                    2
## 2 1659    15          1          2                 2                    2
## 3 1680    15          1          3                 1                   99
## 4 1685    16          2          2                 2                    2
## 5 1692    17          2          3                 2                    3
## 6 1717    15          2          3                 3                    3</code></pre>
<p>Ein häufiger Use-Case für Filter, der bisher noch nicht angesprochen wurde, ist es, fehlende Werte aus den Daten herauszufiltern. Das folgende Codebeispiel sortiert Fälle aus, die in der Variable <code>verbundenheit_europa</code> einen fehlenden Wert (hier als 99 = “Weiß nicht” codiert) haben:</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="datenaufbereitung.html#cb110-1" aria-hidden="true" tabindex="-1"></a>data_filter_na <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb110-2"><a href="datenaufbereitung.html#cb110-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(verbundenheit_europa))</span>
<span id="cb110-3"><a href="datenaufbereitung.html#cb110-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb110-4"><a href="datenaufbereitung.html#cb110-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(data_filter_na)</span></code></pre></div>
<pre><code>## [1] 951</code></pre>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="datenaufbereitung.html#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data_filter_na)</span></code></pre></div>
<pre><code>##   lfdn alter geschlecht bundesland verbundenheit_dtl verbundenheit_europa
## 1 1634    23          1          7                 2                    2
## 2 1636    24          2          6                 2                    3
## 3 1637    23          1          3                 2                    2
## 4 1638    23          2          1                 2                    3
## 5 1639    24          1          7                 3                    3
## 6 1640    24          2          8                 4                    4</code></pre>
</div>
<div id="arrange-fälle-sortieren" class="section level2" number="5.4">
<h2><span class="header-section-number">5.4</span> Arrange: Fälle sortieren</h2>
<p>Mit ´arrange()` lassen sich Fälle in einem Datensatz sortieren. Die Sortierung sollte zwar auf statistische Analysen keinen Einfluss haben, aber dennoch ist dieses Feature nützlich, wenn man z.B. Tabellen hübsch formatieren möchte.</p>
<p>Der Einsatz von <code>arrange()</code> ist sehr simpel. Man muss der Funktion nach dem Datensatz lediglich die Variable übergeben nach der sortiert werden soll, hier z.B. nach dem Alter:</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="datenaufbereitung.html#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="co"># aufsteigend sortieren</span></span>
<span id="cb114-2"><a href="datenaufbereitung.html#cb114-2" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb114-3"><a href="datenaufbereitung.html#cb114-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(alter) <span class="sc">%&gt;%</span> </span>
<span id="cb114-4"><a href="datenaufbereitung.html#cb114-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##   lfdn alter geschlecht bundesland verbundenheit_dtl verbundenheit_europa
## 1 1657    14          2          3                 2                    2
## 2 1662    14          2          7                 1                    1
## 3 1734    14          1         11                 1                    1
## 4 1748    14          1         13                 2                    2
## 5 1753    14          1          2                 2                    2
## 6 1757    14          1          8                 1                    2</code></pre>
<p>Die Daten sind jetzt aufsteigend sortiert. Um eine absteigende Sortierung zu erreichen benötigen wir die Hilfe von <code>desc()</code>. Das sieht dann so aus:</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="datenaufbereitung.html#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="co"># absteigend sortieren</span></span>
<span id="cb116-2"><a href="datenaufbereitung.html#cb116-2" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb116-3"><a href="datenaufbereitung.html#cb116-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(alter))<span class="sc">%&gt;%</span> </span>
<span id="cb116-4"><a href="datenaufbereitung.html#cb116-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##   lfdn alter geschlecht bundesland verbundenheit_dtl verbundenheit_europa
## 1 1636    24          2          6                 2                    3
## 2 1639    24          1          7                 3                    3
## 3 1640    24          2          8                 4                    4
## 4 1648    24          2         14                 2                    3
## 5 1651    24          1          7                 2                    3
## 6 1665    24          2          5                 2                    2</code></pre>
<p>Selbstverständlich kann man auch nach mehreren Variablen sortieren und dabei aufsteigende und absteigende Sortierung nach Belieben mischen:</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="datenaufbereitung.html#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="co"># nach mehreren Variablen sortieren</span></span>
<span id="cb118-2"><a href="datenaufbereitung.html#cb118-2" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb118-3"><a href="datenaufbereitung.html#cb118-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(bundesland, alter, <span class="fu">desc</span>(geschlecht))<span class="sc">%&gt;%</span> </span>
<span id="cb118-4"><a href="datenaufbereitung.html#cb118-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##   lfdn alter geschlecht bundesland verbundenheit_dtl verbundenheit_europa
## 1 2308    14          2          1                 2                    3
## 2 1696    15          2          1                 2                    2
## 3 2080    15          2          1                 2                    2
## 4 2300    15          2          1                 2                    2
## 5 1929    15          1          1                 2                    3
## 6 2112    15          1          1                 3                    2</code></pre>
</div>
<div id="select-variablen-auswählen" class="section level2" number="5.5">
<h2><span class="header-section-number">5.5</span> Select: Variablen auswählen</h2>
<p>Die Funktion <code>select()</code> dient genau wie <code>filter()</code> dazu, den Datensatz zu verkleinern. Jedoch get es bei <code>select()</code> darum, Variablen auszuwählen. Dazu muss man die Variablen, die im Datensatz verbleiben sollen einfach an die Funktion übergeben. Alle anderen Variablen, die nicht vorkommen, werden gelöscht.</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="datenaufbereitung.html#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Variablen auswählen</span></span>
<span id="cb120-2"><a href="datenaufbereitung.html#cb120-2" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb120-3"><a href="datenaufbereitung.html#cb120-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(alter, geschlecht, verbundenheit_europa) <span class="sc">%&gt;%</span> </span>
<span id="cb120-4"><a href="datenaufbereitung.html#cb120-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##   alter geschlecht verbundenheit_europa
## 1    23          1                    2
## 2    24          2                    3
## 3    23          1                    2
## 4    23          2                    3
## 5    24          1                    3
## 6    24          2                    4</code></pre>
<p>Will man nur einzelne Variablen löschen, so geht dies mit einem <code>-</code> vor dem Variablennamen <code>select(data, -alter)</code> löscht also das Alter, alle anderen Variablen würden aber erhalten bleiben.</p>
<p>Es gibt auch die Möglichkeit, Variablen auszuwählen, die einem bestimmten Schema entsprechen, z.B. deren Name mit “vertaruen_medien_” beginnt. Die Syntax dafür ist <code>starts_with("vertrauen_medien_")</code>. Ähnlich kann man auch Variablen in einem bestimmten Bereich auswählen, also alle von <code>var_name_1</code> bis <code>var_name_x</code>. Dafür müsste man bspw. <code>alter:bundesland</code> eingeben.</p>
<p>Zudem kann <code>select()</code> auch dazu verwenden, die Variablen im Datensatz umzusortieren. Dazu schreibt man die Variablen einfach in der neuen Reihenfolge in die Funtion. Beim umsortieren gibt es ebenfalls einige nützliche Helfer. Einer ist bspw. die Funktion <code>everything()</code> - quasi ein Alias für alle Variablen die bis dahin noch nicht genannt wurden.</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="datenaufbereitung.html#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Variablen neu sortieren</span></span>
<span id="cb122-2"><a href="datenaufbereitung.html#cb122-2" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb122-3"><a href="datenaufbereitung.html#cb122-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(lfdn, bundesland, <span class="fu">everything</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb122-4"><a href="datenaufbereitung.html#cb122-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##   lfdn bundesland alter geschlecht verbundenheit_dtl verbundenheit_europa
## 1 1634          7    23          1                 2                    2
## 2 1636          6    24          2                 2                    3
## 3 1637          3    23          1                 2                    2
## 4 1638          1    23          2                 2                    3
## 5 1639          7    24          1                 3                    3
## 6 1640          8    24          2                 4                    4</code></pre>
</div>
<div id="variablen-umcodieren" class="section level2" number="5.6">
<h2><span class="header-section-number">5.6</span> Variablen umcodieren</h2>
<p>Eine häufige Aufgabe bei der Datenaufbereitung ist das Umcodieren. Beim Umcodieren wird das Wertespektrum einer Variable verändert oder verdichtet. Ein Anwendungsfall wäre es, stetige Variable damit in Kategorien einteilen (z.B. Altersgruppen bilden). Ein weiterer Anwendungsfall sind Variablen die “falsch herum” codiert wurden zu drehen: In unserem Mini-Datensatz sind beispielsweise die Variablen zu “Verbundenheit” unintutiv codiert: Ein niedriger Zahlenwert entspricht einer hohen Verbundenheit. Der Wert 1 hat das Werte-Label “sehr verbunden,” der Wert 5 ist hingegen mit “überhaupt nicht verbunden” codiert. Sie können das im Codebuch sehen, aber das folgende Skript verdeutlicht diesen Umstand an der Variable <code>verbundenheit_europa</code>.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="datenaufbereitung.html#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjlabelled)</span>
<span id="cb124-2"><a href="datenaufbereitung.html#cb124-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb124-3"><a href="datenaufbereitung.html#cb124-3" aria-hidden="true" tabindex="-1"></a><span class="co"># einen Vektor mit den Werten einer Variable erzeugen</span></span>
<span id="cb124-4"><a href="datenaufbereitung.html#cb124-4" aria-hidden="true" tabindex="-1"></a>values <span class="ot">=</span> <span class="fu">get_values</span>(data<span class="sc">$</span>verbundenheit_europa) </span>
<span id="cb124-5"><a href="datenaufbereitung.html#cb124-5" aria-hidden="true" tabindex="-1"></a><span class="co"># einen Vektor mit den Labels einer Variable erzeugen</span></span>
<span id="cb124-6"><a href="datenaufbereitung.html#cb124-6" aria-hidden="true" tabindex="-1"></a>labels <span class="ot">=</span> <span class="fu">get_labels</span>(data<span class="sc">$</span>verbundenheit_europa) </span>
<span id="cb124-7"><a href="datenaufbereitung.html#cb124-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb124-8"><a href="datenaufbereitung.html#cb124-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(values, labels) <span class="co"># beide Vektoren zusammenbinden</span></span></code></pre></div>
<pre><code>##      values labels                     
## [1,] &quot;1&quot;    &quot;Sehr verbunden&quot;           
## [2,] &quot;2&quot;    &quot;Ziemlich verbunden&quot;       
## [3,] &quot;3&quot;    &quot;Nicht sehr verbunden&quot;     
## [4,] &quot;4&quot;    &quot;Überhaupt nicht verbunden&quot;
## [5,] &quot;99&quot;   &quot;Weiß nicht&quot;</code></pre>
<p>Intutiver währe es, wenn mit einem hohen Zahlenwert auch eine große Verbundeheit einher ginge. Bei den gepabelten Daten, die hier vorliegen, geht das Umcodieren sehr gut über den Befehl <code>rec()</code> aus dem Paket <code>sjmisc</code>. Der Befehl ist sehr stark an die Logik von SPSS angelehnt.</p>
<p>Der <code>rec()</code>-Befehl fügt sich in die Tydiverse-Logik ein und erwartet als erstes Argument genau wie die <code>dplyr</code>-Funktionen den Dataframe. Deshalb kann man den Befehl ebenfalls sehr gut in der Pipe einsetzen. Das zweite Argeument ist die Variable, die umcodiert werden soll. Man kann hier auch mehrere einsetzen, in unserem Fall alle die mit <code>verbundenheit_</code> beginnen. Das letzte und entscheidende Argument ist die Anweisung zur Umcodierung. Es heißt <code>rec</code> und beinhaltet einen Text mit den Anweisungen in der Form <code>"werte_label = neuer_wert"</code>. Getrennt durch ein Semikolon kann man auch mehrere Anweisungen gleichzeitig übergeben. Jede geplante Umcodierung muss explizit genannt werden. Sollte ein oder mehrere Wert nicht von der Umcodierung betroffen sein, kann man die “restlichen” Werte durch ein <code>"else=copy"</code> auffangen. Dadurch wird der Wert aus der urspründlichen Variable einfach in die neue kopiert. In unserem Beispiel betrifft das den Wert 99 = “weiß nicht.” Die 99 soll ganz unabhängig von der Umcodierung immer diesen Wert beibehalten.</p>
<p>Die Funktion <code>rec()</code> erzeugt neue Variablen, die den gleichen Namen haben wie die ursprünglichen, ergänzt um ein <code>_r</code> am Ende. Diese Endung soll deutlich machen, dass es sich um die recodierte Variante der Variablen handelt.</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="datenaufbereitung.html#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjmisc)</span>
<span id="cb126-2"><a href="datenaufbereitung.html#cb126-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-3"><a href="datenaufbereitung.html#cb126-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb126-4"><a href="datenaufbereitung.html#cb126-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rec</span>(<span class="fu">starts_with</span>(<span class="st">&quot;verbundenheit_&quot;</span>), <span class="at">rec =</span> <span class="st">&quot;Sehr verbunden = 4;</span></span>
<span id="cb126-5"><a href="datenaufbereitung.html#cb126-5" aria-hidden="true" tabindex="-1"></a><span class="st">                                             Ziemlich verbunden = 3;</span></span>
<span id="cb126-6"><a href="datenaufbereitung.html#cb126-6" aria-hidden="true" tabindex="-1"></a><span class="st">                                             Nicht sehr verbunden = 2; </span></span>
<span id="cb126-7"><a href="datenaufbereitung.html#cb126-7" aria-hidden="true" tabindex="-1"></a><span class="st">                                             Überhaupt nicht verbunden = 1;</span></span>
<span id="cb126-8"><a href="datenaufbereitung.html#cb126-8" aria-hidden="true" tabindex="-1"></a><span class="st">                                             else=copy&quot;</span>) </span>
<span id="cb126-9"><a href="datenaufbereitung.html#cb126-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-10"><a href="datenaufbereitung.html#cb126-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Beispielhaft die Variable verbundenheit_europa inkl. recodierter Variante anzeigen:</span></span>
<span id="cb126-11"><a href="datenaufbereitung.html#cb126-11" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb126-12"><a href="datenaufbereitung.html#cb126-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">starts_with</span>(<span class="st">&quot;verbundenheit_dtl&quot;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb126-13"><a href="datenaufbereitung.html#cb126-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##   verbundenheit_dtl verbundenheit_dtl_r
## 1                 2                   3
## 2                 2                   3
## 3                 2                   3
## 4                 2                   3
## 5                 3                   2
## 6                 4                   1</code></pre>
<p>Es ist immer ratsam, im Anschluss zu kontrollieren, ob die Umcodierung auch wie erwartet funktioniert hat. Dies kann z.B. über eine Kreuztabelle geschehen oder wie hier durch ein “nebeneinanderlegen” der beiden Variablen.</p>
<p>Eine kleine Ergänzung noch: Selbstverständlich funktioniert <code>rec()</code> auch mit nicht-gelabelten Daten. In diesem Fall wären einfach die ursprünglichen Werte statt der (nicht vorhandenen) Wertelabels einzutragen: <code>"1=4;2=3;3=2;4=1;else=copy"</code></p>
</div>
<div id="mutate-variablen-berechnen" class="section level2" number="5.7">
<h2><span class="header-section-number">5.7</span> Mutate: Variablen berechnen</h2>
<p>Mit <code>mutate()</code> kann man neue Variablen bilden. Die Syntax dazu folgt dem Schema <code>new_var_name = some calculation</code>. Im nächsten Code-Beispiel wird der Geburtsjahrgang anhand des Alters zum Zeitpunkt der Befragung berechnet. Damit wir die Daten schön vergleichen können, wähle ich die beiden Variablen anschließend aus.</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="datenaufbereitung.html#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Geburtsjahr berechnen</span></span>
<span id="cb128-2"><a href="datenaufbereitung.html#cb128-2" aria-hidden="true" tabindex="-1"></a>new_data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb128-3"><a href="datenaufbereitung.html#cb128-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">jahrgang =</span> <span class="dv">2019</span> <span class="sc">-</span> alter) <span class="sc">%&gt;%</span> </span>
<span id="cb128-4"><a href="datenaufbereitung.html#cb128-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(lfdn, alter, jahrgang)</span>
<span id="cb128-5"><a href="datenaufbereitung.html#cb128-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-6"><a href="datenaufbereitung.html#cb128-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(new_data)</span></code></pre></div>
<pre><code>##   lfdn alter jahrgang
## 1 1634    23     1996
## 2 1636    24     1995
## 3 1637    23     1996
## 4 1638    23     1996
## 5 1639    24     1995
## 6 1640    24     1995</code></pre>
<div id="variablen-unter-einer-bedingung-berechnen" class="section level3" number="5.7.1">
<h3><span class="header-section-number">5.7.1</span> Variablen unter einer Bedingung berechnen</h3>
<p>Man kann Natürlich auch Variablen anhand von logischen Ausdrücken berechnen, also eine Art Filterbedingung dafür zu Rate ziehen welchen Wert die Variable annehmen soll. Es muss dafür wieder mit logischen Ausdrücken gearbeitet werden und wir brauchen eine Funktion die <code>ìfelse()</code> heißt. Die Funktion bekommt drei Argumente:</p>
<ol style="list-style-type: decimal">
<li><p>Den logischen Ausdruck bei dem für jeden Fall zu prüfen ist, ob er für diesen Fall <code>TRUE</code> oder <code>FALSE</code> ist.</p></li>
<li><p>Einen Wert, den die Variable annehmen soll, wenn der Fall <code>TRUE</code> eintritt.</p></li>
<li><p>Einen Wert, den die Variable annehmen soll, wenn der Fall <code>FALSE</code> eintritt.</p></li>
</ol>
<p>Als Beispiel möchte ich eine Variable berechnen die 1 ist, wenn die Verbundenheit zu Europa größer ist als die zu Deutschland und ansonsten 0. Ich nenne sie <code>sieht_sich_als_europaeer</code>.</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="datenaufbereitung.html#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Variable berechnen mit Bedingung</span></span>
<span id="cb130-2"><a href="datenaufbereitung.html#cb130-2" aria-hidden="true" tabindex="-1"></a>data_eu <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb130-3"><a href="datenaufbereitung.html#cb130-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sieht_sich_als_europaeer =</span> <span class="fu">ifelse</span>(verbundenheit_europa <span class="sc">&gt;</span> verbundenheit_dtl, <span class="dv">1</span>, <span class="dv">0</span>)) </span>
<span id="cb130-4"><a href="datenaufbereitung.html#cb130-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-5"><a href="datenaufbereitung.html#cb130-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Für die kontrolle relevante Variablen auswählen</span></span>
<span id="cb130-6"><a href="datenaufbereitung.html#cb130-6" aria-hidden="true" tabindex="-1"></a>data_eu <span class="sc">%&gt;%</span> </span>
<span id="cb130-7"><a href="datenaufbereitung.html#cb130-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(lfdn, verbundenheit_europa, verbundenheit_dtl, sieht_sich_als_europaeer) <span class="sc">%&gt;%</span>   <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##   lfdn verbundenheit_europa verbundenheit_dtl sieht_sich_als_europaeer
## 1 1634                    2                 2                        0
## 2 1636                    3                 2                        1
## 3 1637                    2                 2                        0
## 4 1638                    3                 2                        1
## 5 1639                    3                 3                        0
## 6 1640                    4                 4                        0</code></pre>
<img src="images/ah_dplyr_mutate_blank.png" alt="Artwork by Allison Horst" style="width:1000px;margin-bottom:5px;margin-top:50px">
<div style="color:grey;text-align:right">
Artwork by <a href="https://github.com/allisonhorst/stats-illustrations/">Allison Horst</a>
</div>
<p><br /></p>
</div>
</div>
<div id="summary-daten-verdichten" class="section level2" number="5.8">
<h2><span class="header-section-number">5.8</span> Summary: Daten verdichten</h2>
<p>Die letzte <code>dplyr</code>-Funktion auf die ich hier eingehen möchte ist <code>summarize()</code>. Im ersten Moment wirkt <code>summarize()</code> vielleicht ein bisschen wie eine komplizierte Art deskriptiven Statistiken zu berechnen. Die Funktion kann aber viel mehr und das Entscheidende ist, dass sie nicht wie die im Kapitel "Deskriptive Statistiken vorgestellten Funktionen einfach nur einen Kennwert zurückgibt, sondern einen Datensatz mit dem Ergebnis.</p>
<p>Möglicherweise werden Sie die Funktion zunächst kaum benutzen, aber später wiederentdecken. Der Vollständigkeit halber wird sie trotzdem an dieser Stelle kurz erläutert.</p>
<p>Im ersten Beispiel möchte ich den Mittelwert für die im vorigen Abschnitt berechnete Variable <code>sieht_sich_als_europaeer</code> ausrechnen.</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="datenaufbereitung.html#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test der summarize-Funktion</span></span>
<span id="cb132-2"><a href="datenaufbereitung.html#cb132-2" aria-hidden="true" tabindex="-1"></a>data_eu <span class="sc">%&gt;%</span> </span>
<span id="cb132-3"><a href="datenaufbereitung.html#cb132-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(sieht_sich_als_europaeer, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>##        mean
## 1 0.3198725</code></pre>
<p>Das Ergebnis ist ein Datensatz, der eine neue Variable enthält die <code>mean</code> heißt und nur einen Fall hat. Soweit, so unspannend. Der Wert ist NA und darf als Anteilswert interpretiert werden, da die Variable 0/1-codiert ist. Knapp 32 Prozent der Befragten fühlen sich also stärker mit Europa als mit Deutschland verbunden.</p>
<p>Das geschickte an <code>summarize()</code> ist, dass die Funktion perfekt mit <code>group_by()</code> zusammenarbeitet. Mit <code>group_by()</code> kann man einen Dataframe aufteilen, so dass er dann wie mehrere getrennte Datensätze behandelt wird. Wir könnten also Gruppen bilden und die Anteile in diesen Gruppen rein deskriptiv vergleichen. Mich interessiert bspw. ob regionale Unterschiede gibt. Vergleichen wir mal Hamburg (Wert 2) und Niedersachsen (Wert 3).</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="datenaufbereitung.html#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="co"># summarize mit filter &amp; group_by</span></span>
<span id="cb134-2"><a href="datenaufbereitung.html#cb134-2" aria-hidden="true" tabindex="-1"></a>data_eu <span class="sc">%&gt;%</span></span>
<span id="cb134-3"><a href="datenaufbereitung.html#cb134-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(bundesland <span class="sc">==</span> <span class="dv">2</span> <span class="sc">|</span> bundesland <span class="sc">==</span> <span class="dv">3</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb134-4"><a href="datenaufbereitung.html#cb134-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(bundesland) <span class="sc">%&gt;%</span> </span>
<span id="cb134-5"><a href="datenaufbereitung.html#cb134-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(sieht_sich_als_europaeer, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   bundesland  mean
##   &lt;labelled&gt; &lt;dbl&gt;
## 1 2          0.273
## 2 3          0.375</code></pre>
<p>Natürlich funktioniert das nicht nur mit dem arithmetischen Mittel. Auch andere Berechnungen wären hier denkbar.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="einführung-in-r-1.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="deskriptive-statistik.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/xvariable/r_book/edit/main/05_01_dplyr.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["r_book.pdf"],
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
