<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Kapitel 12 Varianzanalyse | R Kompendium für die kommunikationswissenschaftliche Statistik- und Datenanalyse-Ausbildung am IJK Hannover</title>
  <meta name="description" content="Dieses Buch ist als Nachschlage-Referez für die Statistik-Ausbildung in der Kommunikationswissenschaft gedacht." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Kapitel 12 Varianzanalyse | R Kompendium für die kommunikationswissenschaftliche Statistik- und Datenanalyse-Ausbildung am IJK Hannover" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://bookdown.org/yihui/rmarkdown-cookbook/" />
  
  <meta property="og:description" content="Dieses Buch ist als Nachschlage-Referez für die Statistik-Ausbildung in der Kommunikationswissenschaft gedacht." />
  <meta name="github-repo" content="xvariable/r_book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Kapitel 12 Varianzanalyse | R Kompendium für die kommunikationswissenschaftliche Statistik- und Datenanalyse-Ausbildung am IJK Hannover" />
  
  <meta name="twitter:description" content="Dieses Buch ist als Nachschlage-Referez für die Statistik-Ausbildung in der Kommunikationswissenschaft gedacht." />
  

<meta name="author" content="Julia Niemann-Lenz" />


<meta name="date" content="2021-09-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="t-tests.html"/>
<link rel="next" href="literaturverzeichnis.html"/>
<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-HCCP0H824J"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-HCCP0H824J');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R Kompendium</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Herzlich Willkommen!</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#dank"><i class="fa fa-check"></i>Dank</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#disclaimer"><i class="fa fa-check"></i>Disclaimer</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Einleitung</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#einführung-in-r"><i class="fa fa-check"></i><b>1.1</b> Einführung in R</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="intro.html"><a href="intro.html#s-ist-die-mutter-von-r"><i class="fa fa-check"></i><b>1.1.1</b> S ist die Mutter von R</a></li>
<li class="chapter" data-level="1.1.2" data-path="intro.html"><a href="intro.html#die-philosophie-von-s"><i class="fa fa-check"></i><b>1.1.2</b> Die Philosophie von S</a></li>
<li class="chapter" data-level="1.1.3" data-path="intro.html"><a href="intro.html#die-entwicklung-von-r"><i class="fa fa-check"></i><b>1.1.3</b> Die Entwicklung von R</a></li>
<li class="chapter" data-level="" data-path="intro.html"><a href="intro.html#weiterführende-links"><i class="fa fa-check"></i>Weiterführende Links</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#vorteile-von-r"><i class="fa fa-check"></i><b>1.2</b> Vorteile von R</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#alternativen-zu-r"><i class="fa fa-check"></i><b>1.3</b> Alternativen zu R</a>
<ul>
<li class="chapter" data-level="" data-path="intro.html"><a href="intro.html#weiterführende-links-1"><i class="fa fa-check"></i>Weiterführende Links</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#tipps-zum-r-lernen"><i class="fa fa-check"></i><b>1.4</b> Tipps zum R lernen</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="intro.html"><a href="intro.html#der-anfang-ist-schwer"><i class="fa fa-check"></i><b>1.4.1</b> Der Anfang ist schwer</a></li>
<li class="chapter" data-level="1.4.2" data-path="intro.html"><a href="intro.html#nützliche-hinweise"><i class="fa fa-check"></i><b>1.4.2</b> Nützliche Hinweise</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="installation.html"><a href="installation.html"><i class="fa fa-check"></i><b>2</b> Installation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="installation.html"><a href="installation.html#installationsanleitung-windows"><i class="fa fa-check"></i><b>2.1</b> Installationsanleitung Windows</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="installation.html"><a href="installation.html#erster-schritt-r"><i class="fa fa-check"></i><b>2.1.1</b> Erster Schritt: R</a></li>
<li class="chapter" data-level="2.1.2" data-path="installation.html"><a href="installation.html#zweiter-schritt-rstudio"><i class="fa fa-check"></i><b>2.1.2</b> Zweiter Schritt: RStudio</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="installation.html"><a href="installation.html#installationsanleitung-macos"><i class="fa fa-check"></i><b>2.2</b> Installationsanleitung MacOS</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="installation.html"><a href="installation.html#erster-schritt-r-1"><i class="fa fa-check"></i><b>2.2.1</b> Erster Schritt: R</a></li>
<li class="chapter" data-level="2.2.2" data-path="installation.html"><a href="installation.html#zweiter-schritt-rstudio-1"><i class="fa fa-check"></i><b>2.2.2</b> Zweiter Schritt: RStudio</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="benutzeroberflächen.html"><a href="benutzeroberflächen.html"><i class="fa fa-check"></i><b>3</b> Benutzeroberflächen</a>
<ul>
<li class="chapter" data-level="3.1" data-path="benutzeroberflächen.html"><a href="benutzeroberflächen.html#konsole"><i class="fa fa-check"></i><b>3.1</b> R Konsole</a></li>
<li class="chapter" data-level="3.2" data-path="benutzeroberflächen.html"><a href="benutzeroberflächen.html#rstudio-ide-für-r"><i class="fa fa-check"></i><b>3.2</b> RStudio: IDE für R</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="benutzeroberflächen.html"><a href="benutzeroberflächen.html#rstudio-cloud"><i class="fa fa-check"></i><b>3.2.1</b> RStudio-Cloud</a></li>
<li class="chapter" data-level="3.2.2" data-path="benutzeroberflächen.html"><a href="benutzeroberflächen.html#installation-von-rstudio"><i class="fa fa-check"></i><b>3.2.2</b> Installation von RStudio</a></li>
<li class="chapter" data-level="3.2.3" data-path="benutzeroberflächen.html"><a href="benutzeroberflächen.html#rstudio-benutzeroberfläche"><i class="fa fa-check"></i><b>3.2.3</b> RStudio Benutzeroberfläche</a></li>
<li class="chapter" data-level="3.2.4" data-path="benutzeroberflächen.html"><a href="benutzeroberflächen.html#r-skripte"><i class="fa fa-check"></i><b>3.2.4</b> R-Skripte</a></li>
<li class="chapter" data-level="3.2.5" data-path="benutzeroberflächen.html"><a href="benutzeroberflächen.html#features-von-rstudio"><i class="fa fa-check"></i><b>3.2.5</b> Features von RStudio</a></li>
<li class="chapter" data-level="3.2.6" data-path="benutzeroberflächen.html"><a href="benutzeroberflächen.html#rstudio-anpassen"><i class="fa fa-check"></i><b>3.2.6</b> RStudio anpassen</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html"><i class="fa fa-check"></i><b>4</b> Einführung in R</a>
<ul>
<li class="chapter" data-level="4.1" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#r-syntax"><i class="fa fa-check"></i><b>4.1</b> R-Syntax</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#rechnen-mit-r"><i class="fa fa-check"></i><b>4.1.1</b> Rechnen mit R</a></li>
<li class="chapter" data-level="4.1.2" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#zuweisungsoperatoren"><i class="fa fa-check"></i><b>4.1.2</b> Zuweisungsoperatoren</a></li>
<li class="chapter" data-level="4.1.3" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#objektnamen"><i class="fa fa-check"></i><b>4.1.3</b> Objektnamen</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#kommentare"><i class="fa fa-check"></i><b>4.2</b> Kommentare</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#einfache-kommentare"><i class="fa fa-check"></i><b>4.2.1</b> Einfache Kommentare</a></li>
<li class="chapter" data-level="4.2.2" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#sections"><i class="fa fa-check"></i><b>4.2.2</b> Sections</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#r-pakete"><i class="fa fa-check"></i><b>4.3</b> R-Pakete</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#r-pakete-anzeigen"><i class="fa fa-check"></i><b>4.3.1</b> R-Pakete anzeigen</a></li>
<li class="chapter" data-level="4.3.2" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#r-pakete-installieren"><i class="fa fa-check"></i><b>4.3.2</b> R-Pakete installieren</a></li>
<li class="chapter" data-level="4.3.3" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#pakete-laden"><i class="fa fa-check"></i><b>4.3.3</b> Pakete laden</a></li>
<li class="chapter" data-level="4.3.4" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#dokumentation"><i class="fa fa-check"></i><b>4.3.4</b> Dokumentation</a></li>
<li class="chapter" data-level="4.3.5" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#pakete-finden"><i class="fa fa-check"></i><b>4.3.5</b> Pakete finden</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#funktionen"><i class="fa fa-check"></i><b>4.4</b> Funktionen</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#aufbau-argumente"><i class="fa fa-check"></i><b>4.4.1</b> Aufbau &amp; Argumente</a></li>
<li class="chapter" data-level="4.4.2" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#funktionen-verschachteln"><i class="fa fa-check"></i><b>4.4.2</b> Funktionen verschachteln</a></li>
<li class="chapter" data-level="4.4.3" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#hilfe-für-funktionen"><i class="fa fa-check"></i><b>4.4.3</b> Hilfe für Funktionen</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#doppelte-funktionsnamen"><i class="fa fa-check"></i><b>4.5</b> Doppelte Funktionsnamen</a></li>
<li class="chapter" data-level="4.6" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#eigene-funktionen-schreiben"><i class="fa fa-check"></i><b>4.6</b> Eigene Funktionen schreiben</a></li>
<li class="chapter" data-level="4.7" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#r-projekte"><i class="fa fa-check"></i><b>4.7</b> R-Projekte</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#arbeitsverzeichnis"><i class="fa fa-check"></i><b>4.7.1</b> Arbeitsverzeichnis</a></li>
<li class="chapter" data-level="4.7.2" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#r-projekte-anlegen"><i class="fa fa-check"></i><b>4.7.2</b> R-Projekte anlegen</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#datenimport-und-datenexport"><i class="fa fa-check"></i><b>4.8</b> Datenimport und Datenexport</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#csv-dateien-importieren"><i class="fa fa-check"></i><b>4.8.1</b> CSV-Dateien importieren</a></li>
<li class="chapter" data-level="4.8.2" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#excel-dateien-importieren"><i class="fa fa-check"></i><b>4.8.2</b> Excel-Dateien importieren</a></li>
<li class="chapter" data-level="4.8.3" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#spss-dateien-importieren"><i class="fa fa-check"></i><b>4.8.3</b> SPSS-Dateien importieren</a></li>
<li class="chapter" data-level="4.8.4" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#daten-exportieren-abspeichern"><i class="fa fa-check"></i><b>4.8.4</b> Daten exportieren (abspeichern)</a></li>
<li class="chapter" data-level="4.8.5" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#work_labelled"><i class="fa fa-check"></i><b>4.8.5</b> Arbeit mit gelabelten Daten</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#datenstrukturen"><i class="fa fa-check"></i><b>4.9</b> Datenstrukturen</a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#dataframes"><i class="fa fa-check"></i><b>4.9.1</b> Dataframes</a></li>
<li class="chapter" data-level="4.9.2" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#aufbau-von-dataframes"><i class="fa fa-check"></i><b>4.9.2</b> Aufbau von Dataframes</a></li>
<li class="chapter" data-level="4.9.3" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#atomic_vector_types"><i class="fa fa-check"></i><b>4.9.3</b> Atomare Datentypen</a></li>
<li class="chapter" data-level="4.9.4" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#fehlende-werte"><i class="fa fa-check"></i><b>4.9.4</b> Fehlende Werte</a></li>
<li class="chapter" data-level="4.9.5" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#objekttypen-konvertieren"><i class="fa fa-check"></i><b>4.9.5</b> Objekttypen konvertieren</a></li>
<li class="chapter" data-level="4.9.6" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#faktoren"><i class="fa fa-check"></i><b>4.9.6</b> Faktoren</a></li>
<li class="chapter" data-level="4.9.7" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#listen"><i class="fa fa-check"></i><b>4.9.7</b> Listen</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="einführung-in-r-1.html"><a href="einführung-in-r-1.html#wichtige-funktionen-aus-diesem-kapitel"><i class="fa fa-check"></i>Wichtige Funktionen aus diesem Kapitel</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="rmarkdown.html"><a href="rmarkdown.html"><i class="fa fa-check"></i><b>5</b> RMarkdown</a>
<ul>
<li class="chapter" data-level="5.1" data-path="rmarkdown.html"><a href="rmarkdown.html#rmarkdown-workflow"><i class="fa fa-check"></i><b>5.1</b> RMarkdown Workflow</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="rmarkdown.html"><a href="rmarkdown.html#erster-schritt-rmarkdown-anlegen"><i class="fa fa-check"></i><b>5.1.1</b> Erster Schritt: RMarkdown anlegen</a></li>
<li class="chapter" data-level="5.1.2" data-path="rmarkdown.html"><a href="rmarkdown.html#zweiter-schritt-inhalt-der-rmarkdown-datei"><i class="fa fa-check"></i><b>5.1.2</b> Zweiter Schritt: Inhalt der RMarkdown-Datei</a></li>
<li class="chapter" data-level="5.1.3" data-path="rmarkdown.html"><a href="rmarkdown.html#dritter-schritt-output-erzeugen"><i class="fa fa-check"></i><b>5.1.3</b> Dritter Schritt: Output erzeugen</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="rmarkdown.html"><a href="rmarkdown.html#formatierungen-optionen"><i class="fa fa-check"></i><b>5.2</b> Formatierungen &amp; Optionen</a></li>
<li class="chapter" data-level="5.3" data-path="rmarkdown.html"><a href="rmarkdown.html#weiterführende-links-2"><i class="fa fa-check"></i><b>5.3</b> Weiterführende Links</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html"><i class="fa fa-check"></i><b>6</b> Datenaufbereitung</a>
<ul>
<li class="chapter" data-level="6.1" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#prerequisites"><i class="fa fa-check"></i><b>6.1</b> Prerequisites</a></li>
<li class="chapter" data-level="6.2" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#pipe"><i class="fa fa-check"></i><b>6.2</b> Die Pipe</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#der-aufbau-im-detail"><i class="fa fa-check"></i><b>6.2.1</b> Der Aufbau im Detail</a></li>
<li class="chapter" data-level="6.2.2" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#schlechtere-alternativen-zur-pipe"><i class="fa fa-check"></i><b>6.2.2</b> Schlechtere Alternativen zur Pipe</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#filter-fälle-auswählen"><i class="fa fa-check"></i><b>6.3</b> Filter: Fälle auswählen</a></li>
<li class="chapter" data-level="6.4" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#arrange-fälle-sortieren"><i class="fa fa-check"></i><b>6.4</b> Arrange: Fälle sortieren</a></li>
<li class="chapter" data-level="6.5" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#select-variablen-auswählen"><i class="fa fa-check"></i><b>6.5</b> Select: Variablen auswählen</a></li>
<li class="chapter" data-level="6.6" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#variablen-umcodieren"><i class="fa fa-check"></i><b>6.6</b> Variablen umcodieren</a></li>
<li class="chapter" data-level="6.7" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#variablen-berechnen"><i class="fa fa-check"></i><b>6.7</b> Variablen berechnen</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#summen-und-mittelwertindices"><i class="fa fa-check"></i><b>6.7.1</b> Summen und Mittelwertindices</a></li>
<li class="chapter" data-level="6.7.2" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#berechnen-mit-dplyrmutate"><i class="fa fa-check"></i><b>6.7.2</b> Berechnen mit dplyr::mutate()</a></li>
<li class="chapter" data-level="6.7.3" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#variablen-unter-einer-bedingung-berechnen"><i class="fa fa-check"></i><b>6.7.3</b> Variablen unter einer Bedingung berechnen</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#summarize-daten-verdichten"><i class="fa fa-check"></i><b>6.8</b> Summarize: Daten verdichten</a></li>
<li class="chapter" data-level="" data-path="datenaufbereitung.html"><a href="datenaufbereitung.html#wichtige-funktionen-aus-diesem-kapitel-1"><i class="fa fa-check"></i>Wichtige Funktionen aus diesem Kapitel</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html"><i class="fa fa-check"></i><b>7</b> Deskriptive Statistik</a>
<ul>
<li class="chapter" data-level="7.1" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#datensatz-für-dieses-kapitel"><i class="fa fa-check"></i><b>7.1</b> Datensatz für dieses Kapitel</a></li>
<li class="chapter" data-level="7.2" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#häufigkeitsverteilung"><i class="fa fa-check"></i><b>7.2</b> Häufigkeitsverteilung</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#tabellen"><i class="fa fa-check"></i><b>7.2.1</b> Tabellen</a></li>
<li class="chapter" data-level="7.2.2" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#häufigkeitsdiagramm"><i class="fa fa-check"></i><b>7.2.2</b> Häufigkeitsdiagramm</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#maße-der-zentralen-tendenz-streuung"><i class="fa fa-check"></i><b>7.3</b> Maße der zentralen Tendenz &amp; Streuung</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#nominale-daten"><i class="fa fa-check"></i><b>7.3.1</b> Nominale Daten</a></li>
<li class="chapter" data-level="7.3.2" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#ordinale-daten"><i class="fa fa-check"></i><b>7.3.2</b> Ordinale Daten</a></li>
<li class="chapter" data-level="7.3.3" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#metrische-daten"><i class="fa fa-check"></i><b>7.3.3</b> Metrische Daten</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#schiefe-und-kurtosis"><i class="fa fa-check"></i><b>7.4</b> Schiefe und Kurtosis</a></li>
<li class="chapter" data-level="7.5" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#übersichts-funktionen"><i class="fa fa-check"></i><b>7.5</b> Übersichts-Funktionen</a></li>
<li class="chapter" data-level="" data-path="deskriptive-statistik.html"><a href="deskriptive-statistik.html#wichtige-funktionen-aus-diesem-kapitel-2"><i class="fa fa-check"></i>Wichtige Funktionen aus diesem Kapitel</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="bivariate-statistik.html"><a href="bivariate-statistik.html"><i class="fa fa-check"></i><b>8</b> Bivariate Statistik</a>
<ul>
<li class="chapter" data-level="8.1" data-path="bivariate-statistik.html"><a href="bivariate-statistik.html#kreuztabellen"><i class="fa fa-check"></i><b>8.1</b> Kreuztabellen</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="bivariate-statistik.html"><a href="bivariate-statistik.html#vorbereitung-univariate-verteilung"><i class="fa fa-check"></i><b>8.1.1</b> Vorbereitung: Univariate Verteilung</a></li>
<li class="chapter" data-level="8.1.2" data-path="bivariate-statistik.html"><a href="bivariate-statistik.html#kreuztabelle-ausgeben"><i class="fa fa-check"></i><b>8.1.2</b> Kreuztabelle ausgeben</a></li>
<li class="chapter" data-level="8.1.3" data-path="bivariate-statistik.html"><a href="bivariate-statistik.html#chi-quadrat-cramers-v"><i class="fa fa-check"></i><b>8.1.3</b> Chi-Quadrat &amp; Cramer´s V</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="bivariate-statistik.html"><a href="bivariate-statistik.html#korrelationen"><i class="fa fa-check"></i><b>8.2</b> Korrelationen</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="bivariate-statistik.html"><a href="bivariate-statistik.html#streudiagramm"><i class="fa fa-check"></i><b>8.2.1</b> Streudiagramm</a></li>
<li class="chapter" data-level="8.2.2" data-path="bivariate-statistik.html"><a href="bivariate-statistik.html#kovarianz"><i class="fa fa-check"></i><b>8.2.2</b> Kovarianz</a></li>
<li class="chapter" data-level="8.2.3" data-path="bivariate-statistik.html"><a href="bivariate-statistik.html#korrelation-mit-base-rstats"><i class="fa fa-check"></i><b>8.2.3</b> Korrelation mit <code>base R</code>/<code>stats</code></a></li>
<li class="chapter" data-level="8.2.4" data-path="bivariate-statistik.html"><a href="bivariate-statistik.html#korrelation-mit-psych"><i class="fa fa-check"></i><b>8.2.4</b> Korrelation mit <code>psych</code></a></li>
<li class="chapter" data-level="8.2.5" data-path="bivariate-statistik.html"><a href="bivariate-statistik.html#partialkorrelation"><i class="fa fa-check"></i><b>8.2.5</b> Partialkorrelation</a></li>
<li class="chapter" data-level="8.2.6" data-path="bivariate-statistik.html"><a href="bivariate-statistik.html#korrelationsmatrizen-darstellen"><i class="fa fa-check"></i><b>8.2.6</b> Korrelationsmatrizen darstellen</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bivariate-statistik.html"><a href="bivariate-statistik.html#wichtige-funktionen-aus-diesem-kapitel-3"><i class="fa fa-check"></i>Wichtige Funktionen aus diesem Kapitel</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="grafiken.html"><a href="grafiken.html"><i class="fa fa-check"></i><b>9</b> Grafiken</a>
<ul>
<li class="chapter" data-level="9.1" data-path="grafiken.html"><a href="grafiken.html#drei-basis-funktionen"><i class="fa fa-check"></i><b>9.1</b> Drei Basis-Funktionen</a></li>
<li class="chapter" data-level="9.2" data-path="grafiken.html"><a href="grafiken.html#erste-funktion-plot-objekt-erstellen"><i class="fa fa-check"></i><b>9.2</b> Erste Funktion: Plot-Objekt erstellen</a></li>
<li class="chapter" data-level="9.3" data-path="grafiken.html"><a href="grafiken.html#zweite-funktion-aesthetik-mapping"><i class="fa fa-check"></i><b>9.3</b> Zweite Funktion: Aesthetik Mapping</a></li>
<li class="chapter" data-level="9.4" data-path="grafiken.html"><a href="grafiken.html#dritte-funktion-geom-hinzufügen"><i class="fa fa-check"></i><b>9.4</b> Dritte Funktion: Geom hinzufügen</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="grafiken.html"><a href="grafiken.html#streudiagramm-1"><i class="fa fa-check"></i><b>9.4.1</b> Streudiagramm</a></li>
<li class="chapter" data-level="9.4.2" data-path="grafiken.html"><a href="grafiken.html#jitter-plot"><i class="fa fa-check"></i><b>9.4.2</b> Jitter-Plot</a></li>
<li class="chapter" data-level="9.4.3" data-path="grafiken.html"><a href="grafiken.html#boxplot"><i class="fa fa-check"></i><b>9.4.3</b> Boxplot</a></li>
<li class="chapter" data-level="9.4.4" data-path="grafiken.html"><a href="grafiken.html#violin-plot"><i class="fa fa-check"></i><b>9.4.4</b> Violin-Plot</a></li>
<li class="chapter" data-level="9.4.5" data-path="grafiken.html"><a href="grafiken.html#balkendiagramme"><i class="fa fa-check"></i><b>9.4.5</b> Balkendiagramme</a></li>
<li class="chapter" data-level="9.4.6" data-path="grafiken.html"><a href="grafiken.html#histogramme"><i class="fa fa-check"></i><b>9.4.6</b> Histogramme</a></li>
<li class="chapter" data-level="9.4.7" data-path="grafiken.html"><a href="grafiken.html#liniendiagramme"><i class="fa fa-check"></i><b>9.4.7</b> Liniendiagramme</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="grafiken.html"><a href="grafiken.html#grafiken-speichern"><i class="fa fa-check"></i><b>9.5</b> Grafiken speichern</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>10</b> Regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="regression.html"><a href="regression.html#das-lineare-modell"><i class="fa fa-check"></i><b>10.1</b> Das lineare Modell</a></li>
<li class="chapter" data-level="10.2" data-path="regression.html"><a href="regression.html#bivariate-lineare-regression"><i class="fa fa-check"></i><b>10.2</b> Bivariate lineare Regression</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="regression.html"><a href="regression.html#grafische-darstellung"><i class="fa fa-check"></i><b>10.2.1</b> Grafische Darstellung</a></li>
<li class="chapter" data-level="10.2.2" data-path="regression.html"><a href="regression.html#die-funktion-lm"><i class="fa fa-check"></i><b>10.2.2</b> Die Funktion <code>lm()</code></a></li>
<li class="chapter" data-level="10.2.3" data-path="regression.html"><a href="regression.html#standardisierte-regressionskoeffizienten-β"><i class="fa fa-check"></i><b>10.2.3</b> Standardisierte Regressionskoeffizienten (β)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="t-tests.html"><a href="t-tests.html"><i class="fa fa-check"></i><b>11</b> T-Tests</a>
<ul>
<li class="chapter" data-level="11.1" data-path="t-tests.html"><a href="t-tests.html#datenbeispiel"><i class="fa fa-check"></i><b>11.1</b> Datenbeispiel</a></li>
<li class="chapter" data-level="11.2" data-path="t-tests.html"><a href="t-tests.html#einstichproben-t-test"><i class="fa fa-check"></i><b>11.2</b> Einstichproben-T-Test</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="t-tests.html"><a href="t-tests.html#hypothese-aufstellen"><i class="fa fa-check"></i><b>11.2.1</b> Hypothese aufstellen</a></li>
<li class="chapter" data-level="11.2.2" data-path="t-tests.html"><a href="t-tests.html#daten-explorieren"><i class="fa fa-check"></i><b>11.2.2</b> Daten explorieren</a></li>
<li class="chapter" data-level="11.2.3" data-path="t-tests.html"><a href="t-tests.html#t-test-durchführen"><i class="fa fa-check"></i><b>11.2.3</b> T-Test durchführen</a></li>
<li class="chapter" data-level="11.2.4" data-path="t-tests.html"><a href="t-tests.html#cohens-d"><i class="fa fa-check"></i><b>11.2.4</b> Cohen´s d</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="t-tests.html"><a href="t-tests.html#t-test-für-unabhängige-stichproben"><i class="fa fa-check"></i><b>11.3</b> T-Test für unabhängige Stichproben</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="t-tests.html"><a href="t-tests.html#deskriptive-auswertung"><i class="fa fa-check"></i><b>11.3.1</b> Deskriptive Auswertung</a></li>
<li class="chapter" data-level="11.3.2" data-path="t-tests.html"><a href="t-tests.html#anwendungsvoraussetzungen"><i class="fa fa-check"></i><b>11.3.2</b> Anwendungsvoraussetzungen</a></li>
<li class="chapter" data-level="11.3.3" data-path="t-tests.html"><a href="t-tests.html#levene-test-auf-varianzhomogenität"><i class="fa fa-check"></i><b>11.3.3</b> Levene-Test auf Varianzhomogenität</a></li>
<li class="chapter" data-level="11.3.4" data-path="t-tests.html"><a href="t-tests.html#t-test-durchführen-1"><i class="fa fa-check"></i><b>11.3.4</b> T-Test durchführen</a></li>
<li class="chapter" data-level="11.3.5" data-path="t-tests.html"><a href="t-tests.html#cohens-d-1"><i class="fa fa-check"></i><b>11.3.5</b> Cohen´s d</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="t-tests.html"><a href="t-tests.html#t-test-für-abhängige-stichproben"><i class="fa fa-check"></i><b>11.4</b> T-Test für abhängige Stichproben</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="t-tests.html"><a href="t-tests.html#deskriptiver-vergleich"><i class="fa fa-check"></i><b>11.4.1</b> Deskriptiver Vergleich</a></li>
<li class="chapter" data-level="11.4.2" data-path="t-tests.html"><a href="t-tests.html#levene-tests-durchführen"><i class="fa fa-check"></i><b>11.4.2</b> Levene-Tests durchführen</a></li>
<li class="chapter" data-level="11.4.3" data-path="t-tests.html"><a href="t-tests.html#t-test-durchführen-2"><i class="fa fa-check"></i><b>11.4.3</b> T-Test durchführen</a></li>
<li class="chapter" data-level="11.4.4" data-path="t-tests.html"><a href="t-tests.html#cohens-d-2"><i class="fa fa-check"></i><b>11.4.4</b> Cohen´s d</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="varianzanalyse.html"><a href="varianzanalyse.html"><i class="fa fa-check"></i><b>12</b> Varianzanalyse</a>
<ul>
<li class="chapter" data-level="12.1" data-path="varianzanalyse.html"><a href="varianzanalyse.html#datenbeispiel-1"><i class="fa fa-check"></i><b>12.1</b> Datenbeispiel</a></li>
<li class="chapter" data-level="12.2" data-path="varianzanalyse.html"><a href="varianzanalyse.html#prerequisits"><i class="fa fa-check"></i><b>12.2</b> Prerequisits</a></li>
<li class="chapter" data-level="12.3" data-path="varianzanalyse.html"><a href="varianzanalyse.html#einfaktorielle-varianzanalyse"><i class="fa fa-check"></i><b>12.3</b> Einfaktorielle Varianzanalyse</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="varianzanalyse.html"><a href="varianzanalyse.html#deskriptive-analyse"><i class="fa fa-check"></i><b>12.3.1</b> Deskriptive Analyse</a></li>
<li class="chapter" data-level="12.3.2" data-path="varianzanalyse.html"><a href="varianzanalyse.html#levene-test"><i class="fa fa-check"></i><b>12.3.2</b> Levene-Test</a></li>
<li class="chapter" data-level="12.3.3" data-path="varianzanalyse.html"><a href="varianzanalyse.html#durchführung-der-varianzanalyse"><i class="fa fa-check"></i><b>12.3.3</b> Durchführung der Varianzanalyse</a></li>
<li class="chapter" data-level="12.3.4" data-path="varianzanalyse.html"><a href="varianzanalyse.html#effektstärke"><i class="fa fa-check"></i><b>12.3.4</b> Effektstärke</a></li>
<li class="chapter" data-level="12.3.5" data-path="varianzanalyse.html"><a href="varianzanalyse.html#posthoc-test"><i class="fa fa-check"></i><b>12.3.5</b> Posthoc-Test</a></li>
<li class="chapter" data-level="12.3.6" data-path="varianzanalyse.html"><a href="varianzanalyse.html#ergebnisdarstellung"><i class="fa fa-check"></i><b>12.3.6</b> Ergebnisdarstellung</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="varianzanalyse.html"><a href="varianzanalyse.html#zweifaktorielle-varianzanalyse"><i class="fa fa-check"></i><b>12.4</b> Zweifaktorielle Varianzanalyse</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="varianzanalyse.html"><a href="varianzanalyse.html#deskriptive-analyse-1"><i class="fa fa-check"></i><b>12.4.1</b> Deskriptive Analyse</a></li>
<li class="chapter" data-level="12.4.2" data-path="varianzanalyse.html"><a href="varianzanalyse.html#levene-test-1"><i class="fa fa-check"></i><b>12.4.2</b> Levene-Test</a></li>
<li class="chapter" data-level="12.4.3" data-path="varianzanalyse.html"><a href="varianzanalyse.html#durchführung-einer-mehrfaktoriellen-varianzanalyse"><i class="fa fa-check"></i><b>12.4.3</b> Durchführung einer mehrfaktoriellen Varianzanalyse</a></li>
<li class="chapter" data-level="12.4.4" data-path="varianzanalyse.html"><a href="varianzanalyse.html#visualisierung"><i class="fa fa-check"></i><b>12.4.4</b> Visualisierung</a></li>
<li class="chapter" data-level="12.4.5" data-path="varianzanalyse.html"><a href="varianzanalyse.html#posthoc-tests"><i class="fa fa-check"></i><b>12.4.5</b> Posthoc-Tests</a></li>
<li class="chapter" data-level="12.4.6" data-path="varianzanalyse.html"><a href="varianzanalyse.html#abschließende-beurteilung-des-hypothesentests"><i class="fa fa-check"></i><b>12.4.6</b> Abschließende Beurteilung des Hypothesentests</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="literaturverzeichnis.html"><a href="literaturverzeichnis.html"><i class="fa fa-check"></i>Literaturverzeichnis</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R Kompendium für die kommunikationswissenschaftliche Statistik- und Datenanalyse-Ausbildung am IJK Hannover</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="varianzanalyse" class="section level1" number="12">
<h1><span class="header-section-number">Kapitel 12</span> Varianzanalyse</h1>
<p><em>Die Erarbeitung dieses Kapitels erfolgte auf Basis eines Skripts, welches Daniel Possler 2021 für die Veranstaltung SDA2 erstellt hat. Dieser wiederum nutzte Vorarbeiten von Jule Scheper, Sophie Bruns und Anna Freytag.</em></p>
<p>Im letzten Kapitel haben wir mit dem T-Test ein Verfahren kennengelernt, mit dem wir Unterschiedshypothesen prüfen können, indem die Mittelwerte von zwei Gruppen verglichen werden. Was aber, wenn wir nicht zwei sondern mehr Gruppen haben? Hier kommt die Varianzanalyse ins Spiel. Mit der Varianzanalyse (englisch ANOVA = <strong>an</strong>alysis <strong>o</strong>f <strong>va</strong>riance) ist dies möglich. Genau wie der im letzten Kapitel angewendete T-Test hat die abhängige Variable der Varianzanalyse metrisches Datenniveau und die unabhängige mindestens nominales<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>. Ein Unterschied ist, dass die unabhängige Variable mehr als zwei Ausprägungen haben darf. – Sie muss also nicht zwingend dichotom sein. Ein anderer Unterschied ist, dass als Prüfgröße nicht die T-Verteilung verwendet wird, sondern die von Ronald a. Fisher entwickelte F-Verteilung. Die Prüfgröße heißt deshalb <em>F</em>.</p>
<p>Mit der Varianzanalyse können auch komplexe experimentelle Designs ausgewertet werden, bei denen es z. B. mehr als ein Einflussfaktor berücksichtigt wird. Nimmt man nur einen Einflussfaktor auf, handelt es sich um eine <em>einfaktorielle</em> Varianzanalyse (One-way Anova), bei zwei Faktoren spricht man von einer <em>zweifaktoriellen</em> Varianzanalyse (Two-way Anova) und bei noch mehr Faktoren von einer mehrfaktoriellen Varianzanalyse.</p>
<div id="datenbeispiel-1" class="section level2" number="12.1">
<h2><span class="header-section-number">12.1</span> Datenbeispiel</h2>
<p>Die Daten für dieses Kapitel liefert die BA-Arbeit von Carsten Reichelt (2019). Vielen Dank an dieser Stelle! Carsten Reichelt hat in seiner BA-Arbeit untersucht, ob der Schwierigkeitsgrad eines Videospiels eine Rolle für die Performance und das Erleben von Unterhaltung der Spieler:innen spielt. Um diese Frage zu klären hat er ein Online-Experiment designed in dem N = 248 nutzten Proband:innen vier Minuten lang das Spiel Pac-Man spielen mussten (= Stimulus). Der Stimulus wurde dabei über die drei Schwierigkeitsgrade “einfach” (n = 79), “mittel” (n = 90) und schwer (n = 79) variiert. Die Gruppenzugehörigkeit bildet also die zentrale unabhängige Variable und sie ist dreistufig (einfach, mittel oder schwer). Nach dem Spielen füllten die Proband:innen einen Online-Fragebogen aus, in dem verschiedene weitere, abhängige und unabhängige Variablen erhoben wurden. Außerdem wurde der Highsore, den die Proband:innen erzielten erfasst.</p>
</div>
<div id="prerequisits" class="section level2" number="12.2">
<h2><span class="header-section-number">12.2</span> Prerequisits</h2>
<p>Zunächst benötigen wir natürlich verschiedene Pakete zur Durchfühung der Varianzanalyse:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="varianzanalyse.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co"># für Grafiken und die Pipe</span></span>
<span id="cb1-2"><a href="varianzanalyse.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)   <span class="co"># für Häufigkeitsauszählungen</span></span>
<span id="cb1-3"><a href="varianzanalyse.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rstatix)   <span class="co"># für den Levene-Test</span></span>
<span id="cb1-4"><a href="varianzanalyse.html#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effectsize)<span class="co"># für Eta-Quadrat</span></span>
<span id="cb1-5"><a href="varianzanalyse.html#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(afex)      <span class="co"># zur Berechnung der mehrfaktoriellen Anova</span></span></code></pre></div>
<p>Die Die Daten der Abschlussarbeit von Herrn Reichelt liegen im SPSS-Format .sav. vor. Sie können über das Paket <code>haven</code> geladen werden. Da wir die unabhängigen Variablen für die Varianzanalyse in R als <em>Faktoren</em> benötigen, wandeln wir diese gleich im Anschluss an den Ladevorgang direkt in das benötigte Format um.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="varianzanalyse.html#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> haven<span class="sc">::</span><span class="fu">read_sav</span>(<span class="st">&quot;data/BA–Carsten Reichelt.sav&quot;</span>, <span class="at">user_na =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb2-2"><a href="varianzanalyse.html#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Schwierigkeitsgrad =</span> <span class="fu">factor</span>(Schwierigkeitsgrad, </span>
<span id="cb2-3"><a href="varianzanalyse.html#cb2-3" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;einfach&quot;</span>, <span class="st">&quot;mittel&quot;</span>, <span class="st">&quot;schwer&quot;</span>), </span>
<span id="cb2-4"><a href="varianzanalyse.html#cb2-4" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">ordered =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-5"><a href="varianzanalyse.html#cb2-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">Wettkampfpraeferenz =</span> <span class="fu">factor</span>( v_12_rec,</span>
<span id="cb2-6"><a href="varianzanalyse.html#cb2-6" aria-hidden="true" tabindex="-1"></a>                                       <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;geringe Wettkampfpräferenz&quot;</span>, <span class="st">&quot;hohe Wettkampfpräferenz&quot;</span>),</span>
<span id="cb2-7"><a href="varianzanalyse.html#cb2-7" aria-hidden="true" tabindex="-1"></a>                                       <span class="at">ordered =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb2-8"><a href="varianzanalyse.html#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(lfdn, Schwierigkeitsgrad, Highscore, Wettkampfpraeferenz)</span>
<span id="cb2-9"><a href="varianzanalyse.html#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="varianzanalyse.html#cb2-10" aria-hidden="true" tabindex="-1"></a>df</span></code></pre></div>
<pre><code>## # A tibble: 248 x 4
##     lfdn Schwierigkeitsgrad Highscore Wettkampfpraeferenz       
##    &lt;dbl&gt; &lt;ord&gt;                  &lt;dbl&gt; &lt;ord&gt;                     
##  1    91 mittel                  1950 hohe Wettkampfpräferenz   
##  2    92 einfach                 3890 geringe Wettkampfpräferenz
##  3    93 einfach                 5200 hohe Wettkampfpräferenz   
##  4    98 mittel                  3930 geringe Wettkampfpräferenz
##  5   104 schwer                  1660 geringe Wettkampfpräferenz
##  6   106 mittel                  3280 hohe Wettkampfpräferenz   
##  7   113 einfach                 9000 hohe Wettkampfpräferenz   
##  8   114 einfach                 7920 hohe Wettkampfpräferenz   
##  9   123 mittel                  4800 geringe Wettkampfpräferenz
## 10   135 einfach                 5520 geringe Wettkampfpräferenz
## # … with 238 more rows</code></pre>
</div>
<div id="einfaktorielle-varianzanalyse" class="section level2" number="12.3">
<h2><span class="header-section-number">12.3</span> Einfaktorielle Varianzanalyse</h2>
<p>Bevor wir uns an komplexere Designs wagen, testen wir ersteinmal eine ganz basale Hypothese, die quasi Voraussetzung für die weiteren Analysen in der BA-Arbeit von Herrn Reichelt ist. Im Experiment wird davon ausgagangen, dass die Gruppenzuteilung und der in der jeweiligen Gruppe angewendete Stimulus ursächlich verantwortlich ist für die Varianz zwischen den Gruppen.</p>
<p>Die Hypothese, die zuerst betrachtet wird, ist quasi der Test, ob die Variation durch den Stimulus funktioniert hat (<em>Treatmentcheck</em>). Es sollte so sein, dass der Schwierigkeitsgrad den High-Score beeinflusst, und zwar in “gegenläufiger” (anti-proportionaler) Richtung. Salopp gesagt: Je schwerer das Spiel, desto geringer der Highscore. Anders formuliert könnte die Hypothese so lauten:</p>
<p><em>H1: Der Schwierigkeitsgrad beeinflusst den erzielten Highscore negativ.</em></p>
<div id="deskriptive-analyse" class="section level3" number="12.3.1">
<h3><span class="header-section-number">12.3.1</span> Deskriptive Analyse</h3>
<p>Bevor es an die tatsächliche Prüfung der aufgestellten Hypothese geht, empfiehlt es sie wie immer, sich mit den Mitteln der deskriptiven Statistik und mit Grafiken einen Überblick über die Datenlage zu verschaffen.</p>
<p>Schauen wir uns zunächst die Verteilung der abhängigen Variablen an. Da es sich um eine nominale Variable handelt, interessiert hier vor allem die Häufigkeitsverteilung (und nicht etwa Lage und Streuungsmaße). Zur Anzeige der Häufigkeitsberteilung gibt es viele Wege, etwa <code>table()</code>oder <code>summary()</code>. Damit ich hier auch die realtiven Häufigkeiten erhalte, nutze ich <code>tabyl()</code>aus dem <code>janitor</code>-Paket.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="varianzanalyse.html#cb4-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb4-2"><a href="varianzanalyse.html#cb4-2" aria-hidden="true" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">tabyl</span>(Schwierigkeitsgrad) <span class="sc">%&gt;%</span> </span>
<span id="cb4-3"><a href="varianzanalyse.html#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_rounding</span>(<span class="dv">2</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb4-4"><a href="varianzanalyse.html#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_totals</span>() </span></code></pre></div>
<pre><code>##  Schwierigkeitsgrad   n percent
##             einfach  79    0.32
##              mittel  90    0.36
##              schwer  79    0.32
##               Total 248    1.00</code></pre>
<p>Wir können an dieser Verteilung sehen, dass die Gruppen alle ausreichend groß und ungefähr gleich besetzt sind. Lediglich in Gruppe zwei sind ein paar mehr Versuchspersonen gelandet. Das stört nicht weiter.</p>
<p>Nun schauen wir uns die abhängige Variable, also den Schwierigeitsgrad an. Es ist eine Voraussetzung für die sinnhafte Anwendung der Varianzanalyse, dass die Verteilung dieser Variablen tatsächlich auch im Sample variiert. – Das die Proband:innen also unterschiedliche Scores erzielt haben und nicht etwa alle den gleichen oder einen ähnlichen. Außerdem ist es interessant zu wissen, auf welchem Niveau die Proband:innen Packman spielen. Lassen wir uns also die interessierenden Kennzahlen ausgeben:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="varianzanalyse.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df<span class="sc">$</span>Highscore)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##      30    1870    3305    3918    5658   11130</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="varianzanalyse.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(df<span class="sc">$</span>Highscore)</span></code></pre></div>
<pre><code>## [1] 2394.036</code></pre>
<p>Das sieht prima aus! Der Highscore schwankt zwischen einem Minimum von 30 und einem Maximum von 1.113^{4}. Im Mittel haben die Proband:innen <em>M</em> = 3918 Punkte erzielt, wobei die Verteilung rechtsschief zu sein scheint, da der Medien etwas kleiner als das arithmetische Mittel ist. Auch die Standardabweichung (= Wurzel der Varianz) ist mit 2394.0361856 angemessen hoch. Man kann also sagen, dass der Highscore variiert.</p>
<p>Nützlich ist an dieser Stelle auch ein Histogramm, da man darüber die Verteilung der aV noch detaillierter veranschaulichen kann:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="varianzanalyse.html#cb10-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb10-2"><a href="varianzanalyse.html#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Highscore)) <span class="sc">+</span></span>
<span id="cb10-3"><a href="varianzanalyse.html#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">15</span>)</span></code></pre></div>
<p><img src="r_book_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>Es zeigt tatsächlich eine rechtsschiefe Verteilung, die eine deutliche Spitze im unteren Viertel der Bandbreite an Highscores aufweist.</p>
<p>Mit Hilfe eines Boxplots können wir außerdem die Lage der Mittelwerte und die Variation der Highscores in den einzelnen Gruppen überblicksartig beurteilen. Das ist dann schon ein erster Vorgeschmack auf das zu erwartende Ergebnis des folgenden Hypothesentests – ohne das jedoch geprüft wird, ob die Mittelwerte tatsächlich signifikant von einander abweichen. Zusätzlich lasse ich über <code>stat_summary()</code>noch die arithmetischen Mittel in schwarz in die Grafik einzeichnen, da der Boxplot lediglich die Mediane darstellt.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="varianzanalyse.html#cb11-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb11-2"><a href="varianzanalyse.html#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Schwierigkeitsgrad, </span>
<span id="cb11-3"><a href="varianzanalyse.html#cb11-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">y =</span> Highscore, </span>
<span id="cb11-4"><a href="varianzanalyse.html#cb11-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">color =</span> Schwierigkeitsgrad)) <span class="sc">+</span></span>
<span id="cb11-5"><a href="varianzanalyse.html#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width=</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb11-6"><a href="varianzanalyse.html#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun=</span>mean, <span class="at">shape =</span> <span class="dv">23</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>)</span></code></pre></div>
<p><img src="r_book_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>Tatsächlich, die Mittelwerte in den Gruppen reihen sich genau wie erwartet: Die Personen in der Gruppe “einfach” haben den höchsten Highscore erzielt, die in der Gruppe “schwer” den niedrigsten. Das ist schon einmal vielversprechend für den Hypothesentest, denn diese Reihung hatten wir ja in der Hypothese prognostiziert. Würde sie hier nicht wie erwartet auftreten, könnten wir den Hypothesentest gleich abbrechen.</p>
<p>Noch etwas wird in dem Boxplot ersichtlich: Die Bandbreite an Highscores ist in der Gruppe “einfach” am höchsten: hier liegt sowohl der Minimalwert, als auch der Maximalwert – und zwar über alle Gruppen hinweg! Das sieht man am der senkrechten violetten Linie, die länger ist, als die Linien der anderen beiden Gruppen. Auch die Quartielgrenzen sind recht weit auseinander (das sieht man an der “Box”). In dieser Gruppe scheint also die Streuung relativ groß zu sein. In der gelben Gruppe “schwierig” ist sie hingegen gering. Das erkannt man an der niedriegen “Box” und daran, dass alle Fälle, die außerhalb der Box liegen, noch nicht einmal in Form einer Linie, sondern als Punkte (=Einzelfälle/Ausreißer) dargestellt werden. Die Spieler:innen aus der Gruppe "schwer liegen also viel dichter bei einander als die Spieler:innen der anderen Gruppen.</p>
<p>Der Boxplot prognostiziert folglich eine stark unterschiedliche Varianz oder anders ausgedrückt: <em>fehlende Varianzhomogenität</em>. Aus dem letzten Kapitel <a href="t-tests.html#anwendungsvoraussetzungen">T-Test</a> wissen Sie bereits, dass dies ein Problem sein kann, denn (annähernd) gleiche Varianzen sind eine Anwendungsvoraussetzung, auch für die Varianzanalyse<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a>. Hier kommen wieder der <strong>Levene-Test</strong> und ein korrigierendes Verfahren ins Spiel. Bevor wir also loslegen können mit der eigentlichen Anova schieben wir den Levene-Test ein um sicherzugehen ob die Anwendungsvoraussetzung Varianzhomogenität erfüllt ist oder nicht.</p>
</div>
<div id="levene-test" class="section level3" number="12.3.2">
<h3><span class="header-section-number">12.3.2</span> Levene-Test</h3>
<p>Der Levene-Test prüft – wie im letzten Kapitel beschreiben – ob sich die Varianz in den einzelnen Gruppen unterscheidet (was schlecht wäre) oder nicht (dann wäre die Anwendungsvoraussetzung erfüllt). Bevor wir den Test durchführen, lasse ich mir hier einmal arithmetisches Mittel und die Standardabweichung als standardisiertes Maß der Varianz ausgeben:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="varianzanalyse.html#cb12-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="varianzanalyse.html#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Schwierigkeitsgrad) <span class="sc">%&gt;%</span> </span>
<span id="cb12-3"><a href="varianzanalyse.html#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">M =</span> <span class="fu">round</span>(<span class="fu">mean</span>(Highscore), <span class="dv">0</span>), <span class="at">SD =</span> <span class="fu">round</span>(<span class="fu">sd</span>(Highscore), <span class="dv">0</span>)) </span></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   Schwierigkeitsgrad     M    SD
##   &lt;ord&gt;              &lt;dbl&gt; &lt;dbl&gt;
## 1 einfach             6219  2284
## 2 mittel              3631  1632
## 3 schwer              1946   704</code></pre>
<p>Das sieht tatsächlich nicht so toll aus. Die Standardabweichung ist in der Gruppe “einfach” mit SD = 2284 tatsächlich deutlich höher als in der Gruppe “schwer” mit SD = <code>rdf %&gt;%  filter(Schwierigkeitsgrad == "schwer") %&gt;% summarise(sd(Highscore)) %&gt;% round(0)</code>.</p>
<p>Wir sind vorgewarnt, jetzt wollen wir es genau wissen. Hier kommt der Levene-Test:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="varianzanalyse.html#cb14-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="varianzanalyse.html#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">levene_test</span>(Highscore <span class="sc">~</span> Schwierigkeitsgrad)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##     df1   df2 statistic        p
##   &lt;int&gt; &lt;int&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1     2   245      42.8 1.17e-16</code></pre>
<p>Wie erwartet zweigt der Levene-Test mit p &lt; .001 ein signifikantes Ergebnis. Es ist also von Varianzheterogenität auszugehen und wir benötigen eine Korrektur der Prüfgröße F.</p>
<div id="info_levenef" class="box info">
<p><strong>Funfact</strong></p>
<p>Der Prüfwert des Levene-Tests ist auch ein F-Wert, genau wie der Testwert, der beider Varianzanalyse verwendet wird. Unterschied ist: Bei Levene werden die Varianzen der Gruppen verglichen, bei der Varianzanalyse arithmetische Mittel.</p>
</div>
</div>
<div id="durchführung-der-varianzanalyse" class="section level3" number="12.3.3">
<h3><span class="header-section-number">12.3.3</span> Durchführung der Varianzanalyse</h3>
<p>Nun wissen wir schon eine ganze Menge: Wir haben gesehen, dass sich die mittleren Highscores je nach Schwierigkeitsgrad deutlich unterschieden. Und wir wissen, dass wegen der Varianzhomogenität ein korrigierter Test angewendet werden sollte. Als nächstes prüfen wir die Hypothese mit einem Signifikanztest. Erreicht die Profgröße <em>F</em> einen gewissen Wert sinkt der p-Wert unter die Grenze von p &lt; .05 und man würde in dem experimentellen Setting der BA-Arbeit von Herrn Reichelt davon ausgehen, dass der Schwierigkeitsgrad tatsächlich ursächlich für den erzielten Highscore ist (was ja eine völlig plausible Annahme ist).</p>
<p>Die Standard-Funktion aus <code>base-R</code> zur Berechnung von Varianzanalysen ist <code>aov()</code>. Die Funktion kann jedoch keine Korrektur bei Varianzheterogenität vornehmen, weshalb man lieber auf die Funktion <code>oneway.test()</code>, ebenfalls aus base-R zurückgreifen sollte, die dies ermöglicht. Diese Funktion benötigt zwei Argumente. Das dritte hier angegebene Argument ist optional, es sollte dennoch angegeben werden, damit der mögliche Einsatz der Korrektur bewusst und explizit geschieht. Hier die Argumente von <code>oneway.test()</code>:</p>
<ol style="list-style-type: decimal">
<li><p>Eine Formel <code>formula</code>, die wie folgt aufgebaut ist: <code>abhängige Variable ~ unabhängige Variable</code> (genau wie bei der Regression). Die Tilde <code>~</code> bedeutet soviel wie “wird beeinflusst durch.”</p></li>
<li><p>Ein Datenobjekt <code>data</code> in dem die Variablen und Messwerte zu finden sind, also unser Datensatz.</p></li>
<li><p>Mit dem Argument <code>var.equal</code> lässt sich ein korrigierter Test anfordern. Es steht standardmäßig auf <code>FALSE</code>, so dass nicht von Varianzhomogenität ausgegangen wird und eine s.g. Welch-Korrektur durchgeführt wird. MAn kann es aber auch auf <code>TRUE</code> setzen, wenn der Levene-Test mal auf Varianzhomogenität hinweisen sollte.</p></li>
</ol>
<p>Der Output des erzeugten Modells lässt sich mit <code>summary()</code> ausgeben. Mit <code>tidy()</code> aus dem <code>broom()</code>-Paket erhält man allerdings eine hübschere Tabelle:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="varianzanalyse.html#cb16-1" aria-hidden="true" tabindex="-1"></a>my_model <span class="ot">&lt;-</span> <span class="fu">oneway.test</span>(<span class="at">formula =</span> Highscore <span class="sc">~</span> Schwierigkeitsgrad, </span>
<span id="cb16-2"><a href="varianzanalyse.html#cb16-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> df, </span>
<span id="cb16-3"><a href="varianzanalyse.html#cb16-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span>
<span id="cb16-4"><a href="varianzanalyse.html#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="varianzanalyse.html#cb16-5" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(my_model)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 5
##   num.df den.df statistic  p.value method                                       
##    &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;                                        
## 1      2   136.      150. 3.99e-35 One-way analysis of means (not assuming equa…</code></pre>
<p>Ah sehr schön, ausgegeben werden die Freiheitsgrade (df), der F-Wert (statistic) und der zugehörige, sehr kleine p-Wert (p.value). In der letzten Spalte wird noch einmal die verwendete Methode angeführt (One-way Anova) und in Klammern steht auch, dass keine Varianzhomogenität angenommen wurde, wie gewünscht.</p>
</div>
<div id="effektstärke" class="section level3" number="12.3.4">
<h3><span class="header-section-number">12.3.4</span> Effektstärke</h3>
<p>Als Maß für die Stärke des beobachteten Effekts dient bei der Varianzanalyse <span class="math inline">\(\eta\)</span><sup>2</sup> (Eta-Quadrat). Es berechnet sich aus dem Verhältnis der erklärten Varianz (Quadratsummen zwischen den Gruppen) und der Gesamtvariation. Man kann es mit dem Befehl <code>eta_squared()</code> aus dem <code>effectsize</code>-Paket ausgeben. Um ein Gesamt-Eta (und kein parteilles) zu erhalten sollte man die Option <code>partial</code> auf <code>FALSE</code> setzen und das Konfidenzintervall auf die für uns üblichen 95% (Argument <code>ci = 95</code>):</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="varianzanalyse.html#cb18-1" aria-hidden="true" tabindex="-1"></a>effectsize<span class="sc">::</span><span class="fu">eta_squared</span>(my_model, </span>
<span id="cb18-2"><a href="varianzanalyse.html#cb18-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">partial =</span> <span class="cn">FALSE</span>, </span>
<span id="cb18-3"><a href="varianzanalyse.html#cb18-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">ci =</span> <span class="fl">0.95</span>) </span></code></pre></div>
<pre><code>## Eta2 |       95% CI
## -------------------
## 0.69 | [0.61, 0.75]</code></pre>
<div id="info_levenef" class="box danger">
<p><strong>Achtung, identische Funktionsnamen</strong></p>
<p>Eine genau gleich benannte Funktion <code>eta_squared()</code> gibt es auch im Paket <code>rstatix</code>, das ich für den Levene-Test geladen habe. Diese Funktion funktioniert aber nur mit über <code>aov()</code> erzeugten Objekten. Es ist deshalb unter Umständen wichtig explizit zu machen, dass hier die <code>eta_squared()</code>-Funktion aus dem Paket <code>effectsize</code> verwendet werden soll.</p>
</div>
<p>Zusammenfassend lässt sich sagen, dass die bisherigen Ergebnisse für die H1 sprechen: Der F-Wert ist mit p &lt; .001 signifikant und <span class="math inline">\(\eta\)</span><sup>2</sup> = 0.69 steht für einen starken Zusammenhang. Worüber wir jedoch noch keine Aussage machen können ist, ob sich wirklich alle Gruppen jeweils signifikant von einander unterschieden. Dazu werden Posthoc-Test benötigt.</p>
</div>
<div id="posthoc-test" class="section level3" number="12.3.5">
<h3><span class="header-section-number">12.3.5</span> Posthoc-Test</h3>
<p>Der F-Wert repräsentiert die die kombinierte Signifikanz aller Parameter in der Formel. Es ist ein “Omnibus-Test”: <em>Alle</em> Mitelwertunterschiede dürfen “einsteigen” und werden gleichzeitig getestet. In unserem Fall sind das drei: (1) der Test zwischen “einfach” und “mittel,” der Test zwischen “einfach” und “schwer” sowie (3) der Test zwischen “mittel” und “schwer.” Ist der F-Wert signifikant bedeutet das, dass <em>irgendetwas</em> in dem getesten Modell signifikant ist. Wir wissen aber nicht genau, ob und welcher der drei Mittelwertvergleiche. Sogenannte <em>Poshoc-Tests</em> weisen die Signifikanzen für die einzelnen Mittelwertunterschiede aus.</p>
<div id="info_levenef" class="box warning">
<p><strong>Achtung Alphafehler-Kummulation!</strong></p>
<p>Theoretisch könnte man jetzt einfach hergehen und einen Filter vor die Anova setzen, in dem jeweils eine Gruppe ausgeschlossen wird und nur zwei Gruppen zum Vergleich zugelassen werden. Oder man könnte gleich T-Test mit diesen beiden Gruppen berechnen. Das ist allerdings eine schlechte Idee.</p>
<p>Aus der Inferenzsstatistik-Vorlesung wissen Sie, dass wir bei den hier durchgeführten Nullhypothesentests vorab eine Fehlerwahrscheinlichkeit festlegen, die üblicherweise bei 5 Prozent bzw. bei <span class="math inline">\(\alpha\)</span> = .05 liegt. Das bedeutet wiederum, das wir in 5 Prozemnt der Fälle eine Fehlentscheidung für ein Signifikantes Ergebnis bewusst einkalkulieren. Das wäre rein statistisch jedes zwanzigste Mal. Gerade wenn viele Signifikanztests durchgeführt werden kann es deshalb vermehrt zu solchen Fehlentscheidungen, den so genannten Alpha-Fehlern kommen. Deshalb muss der kummulierte Alpha-Fehler reduziert werden.</p>
<p>Posthoc-Tests machen genau das: (1) Sie testen sehr viele Mittelwertunterschiede – nämlich jeweils einzeln die zwischen jeder Gruppe und jeder anderen Gruppe – und (2) sie korrigieren das Alpha-Fehler-Niveau, so dass es Fehlentscheidungen weniger wahrscheinlich werden und nicht inflationär auftreten. Es gibt viele verschiedene Verfahren für die Alphafehler-Korrektur, die nach ihren jeweiligen Entwicklern benannt sind. Ohne Anspruch auf Vollständigkeit z.B. Bonferoni, Games-Howell, Tamhane und Scheffé. Die Verfahren haben unterschiedliche Anwendungsvoraussetzungen (z.B. Varianzhomogenität) und Vor- und Nachteile. Eine ausführliche Diskussion führt aber an dieser Stelle zu weit.</p>
</div>
<p>Selbstverständlich finden sich Posthoc-Tests wieder in unterschiedlichen R-Paketen. Ich mag das <code>rstatix</code>-Paket, weil es pipeable ist und wir es ohnehin schon geladen haben. Darin finden sich verschiedene Funktionen für Posthoc-Tests:</p>
<ul>
<li>Falls Varianzhomogenität besteht, kann man die Funktion <code>emmeans_test()</code> verwenden. “eenmeans” steht dabei für “estimated marginal means.” Die Funktion benötigtdas Datenobjekt als erstes Argument (eine Tidyverse-Konvention), dann die Formel für die Varianzanalyse und schließlich muss man über <code>p.adjust.method</code> die zu verwendende Korrektur angeben, bspw. <code>"bonferroni"</code></li>
<li>Der Games-Howell-Test berücksichtigt die Welch-Korrektur und ist über die Funktion <code>games_howell_test()</code> nutzbar. Sie benötigt nur das Datenobjekt und die Formel.</li>
</ul>
<p>In unserem Fall brauchen wir natürlich wegen des signifikanten Levene-Tests und der Welch-Korrektur den Games-Howell-Test:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="varianzanalyse.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">games_howell_test</span>(<span class="at">data =</span> df,</span>
<span id="cb20-2"><a href="varianzanalyse.html#cb20-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">formula =</span> Highscore <span class="sc">~</span> Schwierigkeitsgrad)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 8
##   .y.       group1  group2 estimate conf.low conf.high    p.adj p.adj.signif
## * &lt;chr&gt;     &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;       
## 1 Highscore einfach mittel   -2588.   -3321.    -1856. 2.03e-13 ****        
## 2 Highscore einfach schwer   -4274.   -4914.    -3633. 4.89e-10 ****        
## 3 Highscore mittel  schwer   -1685.   -2134.    -1236. 8.04e-14 ****</code></pre>
<p>Die Output-Tabelle zeigt drei Zeilen für die drei paarweisen Mittelwertvergleiche. In den beiden “group”-Spalten steht, welche Gruppen miteinander verglichen werden. Die Spalte “estimate” gibt die Differenz zwischen den Gruppenmittelwerten an und dahinter folgen zwei Spalten für das Konfidenzintervall dieser Differenz. Wenn sich die Grenzen der Konfidenzintervalle nicht überschneiden, spricht dies für einen signifikanten Unterschied. Ob eine Mittelwertdifferenz signifikant ist, kann man aber noch leichter in den letzten beiden Spalten sehen. Dort sind der korrigierte p-Wert bzw. das Siginifikanzlevel angegeben.</p>
<p>Das sich die Konfidenzintervalle nicht in ihrem Wertebereich überschneiden lässt sich übrigens auch sehr schön in einem Balkendiagramm mit zusätzlich eingeblendeten Konfidenzintervallgrenzen visuell darstellen. Wir benötigen dazu einen Datensatz, in dem die Mittelwerte, und die Grenzen der Konfidenzintervalle nach Gruppen aufgesplitztet werden. Zur Berechnung der Grenzen des Konfidenzintervalls wird im folgenden Code die Funktion <code>mean_se()</code> aus dem Paket <code>ggplot2</code> verwendet.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="varianzanalyse.html#cb22-1" aria-hidden="true" tabindex="-1"></a>tab_mean_ci <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="varianzanalyse.html#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Schwierigkeitsgrad) <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="varianzanalyse.html#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">mean_se</span>(Highscore)) <span class="sc">%&gt;%</span> </span>
<span id="cb22-4"><a href="varianzanalyse.html#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Mittelwert =</span> y, <span class="at">CI_lower =</span> ymin, <span class="at">CI_higher =</span> ymax) </span>
<span id="cb22-5"><a href="varianzanalyse.html#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="varianzanalyse.html#cb22-6" aria-hidden="true" tabindex="-1"></a>tab_mean_ci </span></code></pre></div>
<pre><code>## # A tibble: 3 x 4
##   Schwierigkeitsgrad Mittelwert CI_lower CI_higher
##   &lt;ord&gt;                   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 einfach                 6219.    5962.     6476.
## 2 mittel                  3631.    3459.     3803.
## 3 schwer                  1946.    1866.     2025.</code></pre>
<p>Aus diesem Datensatz können wir jekt unseren Plot mit zwei Geomen erstellen. Ein Geom für die Balken und eines für die Konfidenzintervalle.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="varianzanalyse.html#cb24-1" aria-hidden="true" tabindex="-1"></a>tab_mean_ci <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="varianzanalyse.html#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span> (<span class="at">x =</span> Schwierigkeitsgrad, <span class="at">y =</span> Mittelwert)) <span class="sc">+</span> </span>
<span id="cb24-3"><a href="varianzanalyse.html#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Balkendiagramm</span></span>
<span id="cb24-4"><a href="varianzanalyse.html#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">&quot;identity&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;deeppink&quot;</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb24-5"><a href="varianzanalyse.html#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Konfidenzintervalle</span></span>
<span id="cb24-6"><a href="varianzanalyse.html#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">ymin=</span>CI_lower, <span class="at">ymax=</span>CI_higher), <span class="at">width=</span><span class="fl">0.4</span>)</span></code></pre></div>
<p><img src="r_book_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
<div id="ergebnisdarstellung" class="section level3" number="12.3.6">
<h3><span class="header-section-number">12.3.6</span> Ergebnisdarstellung</h3>
<p>Selbstverständlich kann man die Ergebnisse einer Varianzanalyse auch in einer Tabelle darstellen. Macht man jedoch nur eine einzelne Analyse, noch dazu wie in diesem Fall “bloß” einen Treatment-Check, Ist auch die Darstellung im Text möglich. Für unsere Auswertung sieht dass Ergebnis wie folgt aus:</p>
<p>Die Hypothese wird durch die Varianzanalyse mit Welch-Korrektur gestützt, denn sie zeigt mit <span class="math inline">\(F_{korrigiert}\)</span> = 150 ein höchst signifikantes Ergebnis (p &lt; .001). Der beobachtete Effekt ist mit <span class="math inline">\(\eta\)</span><sup>2</sup> = 0.69 als stark zu bezeichnen. Der Posthc-Test nach Games-Howell zeigt: Alle drei Schwierigkeitsgruppen unterscheiden sich in dem erzielten Highscore von einander. Der Mittelwert des Highscores der Gruppe “einfach” ist mit <em>M</em> = 6219 (<em>SD</em> = 2284) der höchste. Der Mittelwert <em>M</em> = 3631 (<em>SD</em> = 1632) der Gruppe “mittel” ist signifikant geringer, und der Mittelwert der Gruppe “schwer” ist mit <em>M</em> = 1946 (<em>SD</em> = 704) wiederum signifikant geringer als dieser. Wenig überraschend führte also ein höherer Schwierigkeitsgrad dazu, dass die Proband:innen einen geringeren Highscore erzielen.</p>
</div>
</div>
<div id="zweifaktorielle-varianzanalyse" class="section level2" number="12.4">
<h2><span class="header-section-number">12.4</span> Zweifaktorielle Varianzanalyse</h2>
<p>Im nächsten Schritt soll eine komplexere Varianzanalyse durchgeführt werden, nämlich eine in der nicht nur ein Einflussfaktor betrachtet wird, sondern gleich zwei. In so einem Modell gibt es drei mögliche Effekte:</p>
<ol style="list-style-type: decimal">
<li>Einen Haupteffekt von Einflussfaktor A</li>
<li>Einen Haupteffekt von Einflussfaktor B</li>
<li>Einen Interaktionseffekt der beiden Einflussfaktoren</li>
</ol>
<div id="info_interactionanova" class="box info">
<p><strong>Haupt- &amp; Interaktionseffekte</strong></p>
<p><em>Haupteffekt</em> bedeutet, dass ein Faktor direkt und unter allen (einbezogenen) Bedingungen auf die abhängige Variable wirkt.</p>
<p>Bei <em>Interaktionseffekten</em> wirken zwei (oder mehr) Faktoren in komplexer Weise zusammen. Der Effekt geht über eine reine Addition der Haupteffekte der beiden Einflussvariablen hinaus. Bei einer Interaktion ist die Wirkung eines Faktors abhängig von den Ausprägungen des anderen Faktors. Das heißt zum Beispiel, dass sich die Wirkung bei gleichzeitigem Auftreten besonders verstärken kann. Es sind aber auch Abschwächungseffekte denkbar, oder dass eine bestimmte Wirkung von Faktor A nur auftritt, wenn auch Faktor B zu einem gewissen Grad gegeben ist. – Der <em>F</em>-Wert verändert sich.</p>
<p>Interaktionseffekte zu untersuchen ist natürlich besonders spannend.</p>
</div>
<p>Wir greifen in diesem Beispiel wieder auf die Daten von Carsten Reichelt zurück und nehmen nun einen zusätzlichen Einflussfaktor hinzu, nämlich die Wettkampfpräferenz. Dieses Konstrukt drückt aus, inwiefern ein:e Spieler:in bereit ist, sich einem Wettkampf zu stellen. Die Variable ist nominal/dichotom und hat zwei Ausprägungen: geringe und hohe Wettkampfpräferenz.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="varianzanalyse.html#cb25-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb25-2"><a href="varianzanalyse.html#cb25-2" aria-hidden="true" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">tabyl</span>(Wettkampfpraeferenz) <span class="sc">%&gt;%</span> </span>
<span id="cb25-3"><a href="varianzanalyse.html#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_rounding</span>(<span class="dv">2</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb25-4"><a href="varianzanalyse.html#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_totals</span>() </span></code></pre></div>
<pre><code>##         Wettkampfpraeferenz   n percent
##  geringe Wettkampfpräferenz 131    0.53
##     hohe Wettkampfpräferenz 117    0.47
##                       Total 248    1.00</code></pre>
<p>Für unser Hypothesenkonstrukt bedeutet das, dass wir nun drei Hypothesen haben:</p>
<p><em>H1: Der Schwierigkeitsgrad beeinflusst den Highscore negativ (siehe oben).</em></p>
<p><em>H2: Die Wettkampfpräferenz beeinflusst den Highscore positiv.</em></p>
<p><em>H3: Es gibt einen Interaktionseffekt zwischen Schwierigkeitsgrad und Wettkampfpräferenz.</em></p>
<p>Für H3 sollten wir natürlich auch überlegen, welcher Art die Interaktion sein könnte. Ich lehne mich jetzt mal aus dem Fenster und prognostiziere, dass man erwarten könnte, dass der Einfluss von Wettkampfpräferenz mit steigendem Schwierigkeitsgrad abnimmt. Meine Begründung dafür wäre, dass man bei einem hohen Schwierigkeitsgrad weniger Einfluss auf den Highscore hat, selbst wenn man eine hohe Wettkampfpräferenz hat. Das Ergebnis des Highscores ist schließlich auch noch von vielen anderen Punkten abhängig, wie z.B. Spielerfahrung oder generelle Reaktionsgeschwindigkeit. Meine präzisierte H3 lautet also:</p>
<p><em>H3: Bei zunehmendem Schwierigkeitsgrad nimmt der Einfluss der Wettkampfpräferenz ab.</em></p>
<div id="info_interactionanova" class="box warning">
<p><strong>Muss H1 noch einmal geprüft werden? Ja!</strong></p>
<p>Man könnte ja denken, dass man H1 auch weglassen könnte, schließlich haben wir sie im vorigen Abschnitt bereits geprüft. Allerdings kann es natürlich sein, dass sich der gefundene Effekt bei der Hinzunahme neuer Einflussfaktoren verändert, z.B. geringer ausfällt (der <em>F</em>-Wert würde in diesem Fall geringer und damit auch die Signifikanz).</p>
<p>Außerdem können wir die Effekte beider Einflussfaktoren miteinander vergleichen, wenn wir beide aufnehmen.</p>
</div>
<div id="deskriptive-analyse-1" class="section level3" number="12.4.1">
<h3><span class="header-section-number">12.4.1</span> Deskriptive Analyse</h3>
<p>Wie immer: Vor dem Signifikanztest wird deskriptiv ausgewertet. Es muss festgestellt werden, ob die Mittelwerte in die Prognostizierte Richtung weisen. Für H1 und den Schwierigkeitsgrad haben wir dies im letzten Abschnitt bereits bestätigt.</p>
<p>Aber auch für den zweiten Haupteffekt und die Wettkampfpräferenz (H2) sieht es gut aus, denn tatsächlich ist der Highscore der Probanden höher, wenn die Wettkampfpräferenz höher ist.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="varianzanalyse.html#cb27-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="varianzanalyse.html#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Wettkampfpraeferenz) <span class="sc">%&gt;%</span> </span>
<span id="cb27-3"><a href="varianzanalyse.html#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>(), </span>
<span id="cb27-4"><a href="varianzanalyse.html#cb27-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">M =</span> <span class="fu">round</span>(<span class="fu">mean</span>(Highscore)),</span>
<span id="cb27-5"><a href="varianzanalyse.html#cb27-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">SD =</span> <span class="fu">round</span>(<span class="fu">sd</span>(Highscore)))</span></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   Wettkampfpraeferenz            n     M    SD
##   &lt;ord&gt;                      &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 geringe Wettkampfpräferenz   131  3550  2080
## 2 hohe Wettkampfpräferenz      117  4331  2652</code></pre>
<p>Nun zum Interaktionseffekt. Um die Werte zu veranschaulichen, gruppieren wir nicht nur nach einer unabhängigen Variablen, sondern nach beiden. Weil wir diese Tabelle später noch einmal benötigen, wird sie als Objekt <code>desc_table</code> abgespeichert.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="varianzanalyse.html#cb29-1" aria-hidden="true" tabindex="-1"></a>desc_table <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb29-2"><a href="varianzanalyse.html#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Schwierigkeitsgrad, Wettkampfpraeferenz) <span class="sc">%&gt;%</span> </span>
<span id="cb29-3"><a href="varianzanalyse.html#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>(), </span>
<span id="cb29-4"><a href="varianzanalyse.html#cb29-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">M =</span> <span class="fu">round</span>(<span class="fu">mean</span>(Highscore)),</span>
<span id="cb29-5"><a href="varianzanalyse.html#cb29-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">SD =</span> <span class="fu">round</span>(<span class="fu">sd</span>(Highscore)))</span>
<span id="cb29-6"><a href="varianzanalyse.html#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="varianzanalyse.html#cb29-7" aria-hidden="true" tabindex="-1"></a>desc_table </span></code></pre></div>
<pre><code>## # A tibble: 6 x 5
## # Groups:   Schwierigkeitsgrad [3]
##   Schwierigkeitsgrad Wettkampfpraeferenz            n     M    SD
##   &lt;ord&gt;              &lt;ord&gt;                      &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 einfach            geringe Wettkampfpräferenz    37  5267  2196
## 2 einfach            hohe Wettkampfpräferenz       42  7058  2037
## 3 mittel             geringe Wettkampfpräferenz    50  3768  1660
## 4 mittel             hohe Wettkampfpräferenz       40  3458  1601
## 5 schwer             geringe Wettkampfpräferenz    44  1858   617
## 6 schwer             hohe Wettkampfpräferenz       35  2056   796</code></pre>
<p>Diese Tabelle ist etwas unübersichtlich. Aber eigentlich ist es auch nicht so schlimm, wenn man weiß, wonach man suchen muss. Es ist hier relevant zu schauen, ob sich die Mittelwerte in zusammengehörigen Zeilen unterschieden, z.B. also die beiden Zeilen “Schwierigkeitsgrad leicht.” Tatsächlich ist in diesen beiden Zeilen ein deutlicher Mittelwertunterschied zu finden. Bei “mittel” und “schwer” ist hingegen kaum eine Differenz.</p>
<p>An den Werten für n können wir sehen, dass es auch für jede Kombination der beiden Einflussfaktoren im Datensatz eine beruhigend hohe Anzahl an n &gt; 30 Fällen gibt. Wir können deshalb nach dem zentralen Grenzwerttheorem davon ausgehen, dass sich Stichprobenmittelwerte unterschiedlicher Stichproben normal verteilen würden, selbst in den jetzt sechs Untergruppen.</p>
<p>Zur visuellen Analyse lässt sich der Boxplot über die <code>ggplot</code>-Funktion <code>facet_wrap</code> leicht so aufsplitten, dass alle sechs Gruppen sichtbar werden:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="varianzanalyse.html#cb31-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb31-2"><a href="varianzanalyse.html#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Schwierigkeitsgrad, <span class="at">y =</span> Highscore, <span class="at">color =</span> Schwierigkeitsgrad)) <span class="sc">+</span></span>
<span id="cb31-3"><a href="varianzanalyse.html#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width=</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb31-4"><a href="varianzanalyse.html#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun=</span>mean, <span class="at">shape =</span> <span class="dv">23</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb31-5"><a href="varianzanalyse.html#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(Wettkampfpraeferenz))</span></code></pre></div>
<p><img src="r_book_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>Augenscheinlich hat sich die Lage durch die Aufteilung in nun sechs Gruppen nicht wesentlich verschlimmert, denn die jeweils gleichfarbigen Box-Plots weisen immer die höchste Ähnlichkeit zueinander auf und sind von den andersfarbigen immer deutlich verschieden.</p>
</div>
<div id="levene-test-1" class="section level3" number="12.4.2">
<h3><span class="header-section-number">12.4.2</span> Levene-Test</h3>
<p>Wir wissen bereits aus dem vorigen Abschnitt, dass wir es hinsichtlich der Gruppenvariable Schwierigkeit mit heterogenen Varianzen bei der Variable Highscore zu tun haben. Außerdem existiert für die Mehrfaktorielle Varianzanalyse leider keine Welch-Korrektur. Der Vollständigkeit halber, wird hier dennoch demonstriert, wie eine Analyse der unterschiedlichen Streuung bei einer Zweifaktoriellen Varianzanalyse aussieht.</p>
<p>Zuerst der Levene-Test für den Einflussfaktor Wettkampfpräferenz:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="varianzanalyse.html#cb32-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb32-2"><a href="varianzanalyse.html#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">levene_test</span>(Highscore <span class="sc">~</span> Wettkampfpraeferenz)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##     df1   df2 statistic       p
##   &lt;int&gt; &lt;int&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1     1   246      8.03 0.00499</code></pre>
<p>Ergebnis: Ebenfalls signifikant, also ungleiche Varianzen.</p>
<p>Und da wir uns in H3 auch für den Interaktionseffekt interessieren folgt noch ein multifaktorieller Levene-Test. Die Interaktion wird eingebracht über den Operator <code>*</code> (Asterisk/Sternchen) in der Formel. Der Asterisk bedeutet soviel wie “interagiert mit.”</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="varianzanalyse.html#cb34-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb34-2"><a href="varianzanalyse.html#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">levene_test</span>(Highscore <span class="sc">~</span> Schwierigkeitsgrad <span class="sc">*</span> Wettkampfpraeferenz)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##     df1   df2 statistic        p
##   &lt;int&gt; &lt;int&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1     5   242      13.2 2.33e-11</code></pre>
<p>Wie zu erwarten, ein drittes signifikantes Ergebnis. Wir können also auf keinen Fall von Varianzhomogenität ausgehen. Dieses Wissen bleibt insofern ohne Konsequenzen, als dass wir hier eine ganz normale zweifaktorielle Varianzanalyse berechnen werden, weil die Welch-Korrektur für dieses Verfahren fehlt. Wir behalten aber im Hinterkopf, dass das Ergebnis der nun folgenden Analyse möglicherweise verzerrt ist, weil die Anwendungsvoraussetzung der Varianzhomogenität verletzt wird.</p>
</div>
<div id="durchführung-einer-mehrfaktoriellen-varianzanalyse" class="section level3" number="12.4.3">
<h3><span class="header-section-number">12.4.3</span> Durchführung einer mehrfaktoriellen Varianzanalyse</h3>
<p>Nun folgt der Signifikanztest, bzw. die Signifikanztests, es sind ja mehrere und zwar gleichzeitig. Es gibt – wie so oft – viele Pakete mit denen man eine zweifaktorielle Varianzanalyse berechnen könnte, z.B. auch das Paket <code>rstatix</code>, das wir ja bereits geladen haben. Ich habe mich hier jedoch für das <code>afex</code>-Paket entschieden. Es ist ein spezielles Paket zur Berechnung von Anovas mit Experimentaldaten und bietet dabei viele Möglichkeiten. – Auch wenn Ihre Analysen komplexer werden und über das hier gezeigte hinausgehen, können Sie bei dem Paket bleiben.</p>
<p>Bevor es losgeht, eine Anmerkung vorab: Es gibt bei der mehrfaktoriellen Varianzanalyse unterschiedliche “Typen.” Sie unterscheiden sich darin, wie die Abweichungen der individuellen Messungen vom Gesamtmittelwert den einzelnen Faktoren zugeschlagen werden. Dieses Thema kann hier nicht vertieft werden. Wichtig ist aber, dass wir für die unsere Berechnung die Quadratsummenzerlegung <em>Typ III</em> benötigen, dies bietet das base-Paket nicht.</p>
<pre><code>## Coefficient covariances computed by hccm()</code></pre>
<pre><code>## ANOVA Table (type III tests)
## 
##                                   Effect DFn DFd       F        p p&lt;.05   ges
## 1                     Schwierigkeitsgrad   2 242 138.255 9.04e-41     * 0.533
## 2                    Wettkampfpraeferenz   1 242   7.522 7.00e-03     * 0.030
## 3 Schwierigkeitsgrad:Wettkampfpraeferenz   2 242   9.640 9.37e-05     * 0.074</code></pre>
<p>Die Funktion <code>aov_car</code> aus dem <code>afex</code>-Paket benötigt eine Formel der Form <code>abhängige Variable ~ unabhängige Variable</code>, genau wie beim Levene-Test. Es gibt aber noch eine Besonderheit: Angegeben werden muss außerdem noch ein “Fehlerterm.” Der Fehlerterm stellt in dem Modell die nicht erklärte Varianz dar, die jeder Messpunkt aufweist. Es ist wichtig, dass hier eine Variable eingesetzt wird, die für jeden Fall im Datensatz einen <em>eineindeutigen</em> Wert hat (= kein Wert darf doppelt vorkommen). Hier bietet sich die “laufende Nummer,” also die Variable <code>lfdn</code> an.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="varianzanalyse.html#cb38-1" aria-hidden="true" tabindex="-1"></a>my_model <span class="ot">&lt;-</span> afex<span class="sc">::</span><span class="fu">aov_car</span>(Highscore <span class="sc">~</span> Schwierigkeitsgrad <span class="sc">+</span> Wettkampfpraeferenz <span class="sc">+</span> </span>
<span id="cb38-2"><a href="varianzanalyse.html#cb38-2" aria-hidden="true" tabindex="-1"></a>                                      Schwierigkeitsgrad <span class="sc">*</span> Wettkampfpraeferenz <span class="sc">+</span></span>
<span id="cb38-3"><a href="varianzanalyse.html#cb38-3" aria-hidden="true" tabindex="-1"></a>                                      <span class="fu">Error</span>(lfdn), </span>
<span id="cb38-4"><a href="varianzanalyse.html#cb38-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">data =</span> df)</span></code></pre></div>
<pre><code>## Contrasts set to contr.sum for the following variables: Schwierigkeitsgrad, Wettkampfpraeferenz</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="varianzanalyse.html#cb40-1" aria-hidden="true" tabindex="-1"></a>my_model</span></code></pre></div>
<pre><code>## Anova Table (Type 3 tests)
## 
## Response: Highscore
##                                   Effect     df        MSE          F  ges
## 1                     Schwierigkeitsgrad 2, 242 2547712.45 138.25 *** .533
## 2                    Wettkampfpraeferenz 1, 242 2547712.45    7.52 ** .030
## 3 Schwierigkeitsgrad:Wettkampfpraeferenz 2, 242 2547712.45   9.64 *** .074
##   p.value
## 1   &lt;.001
## 2    .007
## 3   &lt;.001
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;+&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Sehr schön, alle <em>F</em>-Werte sind signifikant! Das spricht für die Hypothesen. Weil die deskriptive Analyse der Haupteffekte auch in die richtige Richtung zeigte, können H1 und H2 jetzt schon als durch die Daten bestätigt angesehen werden. Bei H3, der Interaktionshypothese ist es nicht ganz so klar, aber irgendwas signifikantes scheint es auch hier zu geben, zum Verständnis hilft ein Interaktionsplot.</p>
<p>Zuvor berechnen wir aber noch schnell die Effektstärken des Modells, das nicht-partielle <span class="math inline">\(\eta^2^\)</span>:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="varianzanalyse.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eta_squared</span>(my_model, <span class="at">partial =</span> <span class="cn">FALSE</span>, <span class="at">ci =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## Type 3 ANOVAs only give sensible and informative results when covariates are
##   mean-centered and factors are coded with orthogonal contrasts (such as those
##   produced by &#39;contr.sum&#39;, &#39;contr.poly&#39;, or &#39;contr.helmert&#39;, but *not* by the
##   default &#39;contr.treatment&#39;).</code></pre>
<pre><code>## # Effect Size for ANOVA (Type III)
## 
## Parameter                              | Eta2 |       95% CI
## ------------------------------------------------------------
## Schwierigkeitsgrad                     | 0.51 | [0.42, 0.58]
## Wettkampfpraeferenz                    | 0.01 | [0.00, 0.06]
## Schwierigkeitsgrad:Wettkampfpraeferenz | 0.04 | [0.00, 0.09]</code></pre>
<p>Eindeutig die größte Effektstärke zeigt der Haupteffekt des Schwierigkeitsgrades (H1). – Gegenüber dem Test mit der einfaktoriellen Varianzanalyse fällt es jedoch geringfügig kleiner aus. Die anderen beiden Effekte sind irgendwie existent, aber vergleichsweise gering.</p>
</div>
<div id="visualisierung" class="section level3" number="12.4.4">
<h3><span class="header-section-number">12.4.4</span> Visualisierung</h3>
<p>Die Visualisierung von Interaktionseffekten hilft erheblich bei der Interpretation. Am einfachsten ist, es, wenn wir als Basis für die Visualisierung die Tabelle benutzen, die wir im Abschnitt <a href="varianzanalyse.html#deskriptive-analyse-1">Deskriptive Analyse</a> erzeugt hatten. Wir brauchen aus dieser Tabelle die beiden Einflussvariablen und die Mittelwerte:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="varianzanalyse.html#cb45-1" aria-hidden="true" tabindex="-1"></a>desc_table <span class="sc">%&gt;%</span> </span>
<span id="cb45-2"><a href="varianzanalyse.html#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Schwierigkeitsgrad, Wettkampfpraeferenz, M)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
## # Groups:   Schwierigkeitsgrad [3]
##   Schwierigkeitsgrad Wettkampfpraeferenz            M
##   &lt;ord&gt;              &lt;ord&gt;                      &lt;dbl&gt;
## 1 einfach            geringe Wettkampfpräferenz  5267
## 2 einfach            hohe Wettkampfpräferenz     7058
## 3 mittel             geringe Wettkampfpräferenz  3768
## 4 mittel             hohe Wettkampfpräferenz     3458
## 5 schwer             geringe Wettkampfpräferenz  1858
## 6 schwer             hohe Wettkampfpräferenz     2056</code></pre>
<p>Was im Interaktionsdiagramm dargestellt werden soll, ist genau das, was oben in der Tabelle steht: Die Mittelwerte des Highscores und zwar in Abhängigkeit von den beiden unabhängigen Variablen. Hätten wir nur einen Einflussfaktor, würden wir das mit einem Balkendiagramm machen (siehe oben: Schwierigkeitsgrad auf die x-Achse, Mittelwert des Highscores auf die y-Achse).</p>
<p>Bei zwei Faktoren bietet sich ein Liniendiagramm an. Der zweite Faktor kann dann durch unterschiedliche Linien (Argument <code>group</code>) dargestellt werden, die zur besseren Übersichtlichkeit auch noch verschieden eingefärbt werden können (Argument <code>color</code>).</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="varianzanalyse.html#cb47-1" aria-hidden="true" tabindex="-1"></a>desc_table <span class="sc">%&gt;%</span> </span>
<span id="cb47-2"><a href="varianzanalyse.html#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Schwierigkeitsgrad, <span class="at">y =</span> M, </span>
<span id="cb47-3"><a href="varianzanalyse.html#cb47-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">group =</span> Wettkampfpraeferenz, <span class="at">color =</span> Wettkampfpraeferenz)) <span class="sc">+</span>       </span>
<span id="cb47-4"><a href="varianzanalyse.html#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb47-5"><a href="varianzanalyse.html#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Ab hier nur noch &quot;Aufhübschung&quot; des Plots</span></span>
<span id="cb47-6"><a href="varianzanalyse.html#cb47-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">8000</span>) <span class="sc">+</span></span>
<span id="cb47-7"><a href="varianzanalyse.html#cb47-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Schwierigkeitsgrad&quot;</span>, </span>
<span id="cb47-8"><a href="varianzanalyse.html#cb47-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Mittelwert Highscore&quot;</span>) <span class="sc">+</span> </span>
<span id="cb47-9"><a href="varianzanalyse.html#cb47-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb47-10"><a href="varianzanalyse.html#cb47-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;green&quot;</span>, <span class="st">&quot;deeppink&quot;</span>))</span></code></pre></div>
<p><img src="r_book_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>In dem Interaktionsdiagramm zeigt sich, dass die von mir Prognostizierte Interaktion vor allem im einfachen Schwierigkeitsgrad zum Tragen kommt. Hier ist es tatsächlich so, dass Probandinnen mit hoher Wettkampfpräferenz deutlich besser abschneiden als solche mit niedriger. Auf mittlerem Schwierigkeitsgrad ist die Tendenz jedoch umgedreht. Hier sind Personen mit niedriger Wettkampfpräferenz etwas besser. Der Mittelwertunterschied ist jedoch gering. Bei schweren Schwierigkeitsgrad dreht es sich wieder, aber auch hier ist die Mittelwertdifferenz gering. Es ist also kompliziert. Möglicherweise gibt es einen zusätzlichen Effekt, bei dem Personen mit hoher Wettkampfpräferenz durch einen besonders schweren Schwierigkeitsgrad zusätzlich angespornt werden einen hohen Highscore zu erzielen. Um das zu untersuchen sind unsere Daten aber leider nicht differenziert genug. Festzuhalten ist aber, dass sich die H3 (A-Version) bestätigen lässt (das zeigt der <em>F</em>-Wert oben) und dass zumindest die visuellen Ergebnisse für Gruppe “leicht” für die präzisierte B-Version der H3 sprechen.</p>
<p>Es stellt sich jetzt natürlich die Frage, welche der beobachteten Mittelwertunterschiede sind signifikant?</p>
</div>
<div id="posthoc-tests" class="section level3" number="12.4.5">
<h3><span class="header-section-number">12.4.5</span> Posthoc-Tests</h3>
<p>Bis hierhin haben wir festgestellt, dass sich wohl alle drei Hypothesen bestätigen lassen. Müssen wir einen erneuten Posthoc-Test durchführen? Und wenn ja für welche Hypothesen?</p>
<p>Für H1 (Haupteffekt des Schwierigkeitsgrades) haben wir den Posthoc-Test bereits im ersten Abschnitt bei der einfaktoriellen Varianzanalyse ausgeführt. Das ERgebnis würde hier nicht anders ausfallen.</p>
<p>Für H2 (Haupteffekt der Wettkampfpräferenz) brauchen wir keinen Posthoc-Test, denn der Faktor Wettkampfpräferenz hat nur zwei Ausprägungen. Die Varianzanalyse hat einen signifikanten Haupteffekt ergeben, es ist klar das sich nur diese beiden unterschieden können (um beim Bild des Omnibustests zu bleiben: Es sitzt nur ein Mittelwertunterschied im Bus).</p>
<p>Für H3 (Interaktion) wäre ein Posthoc-Test natürlich interessant. Es wäre wichtig zu wissen, ob sich die Personen mit hoher vs. niedriger Wettkampfpräferenz in der Gruppe leichter Schwierigkeitsgrad tatsächlich signifikant unterscheiden. Und natürlich auch, ob in den anderen Schwierigkeitsgraden signifikante Unterschiede vorliegen.</p>
<p>Ich habe leider noch keine elegante Version gefunden, mit der man in R einen Posthoc-Test für Interaktionseffekte rechnen kann – für Hinweise wäre ich dankbar. Bis ich diesen Hinweis erhalten habe, behelfe ich mich damit, dass ich aus den beiden Faktoren einen neue, kombinierte Gruppenvariable bilde und diese dann in den Posthoc-Test gebe.</p>
<p>Der folgende Code ist advanced, der Vollständigkeit halber zeige ich ihn hier dennoch:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="varianzanalyse.html#cb48-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb48-2"><a href="varianzanalyse.html#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="co">#eine neue Gruppenvariable erstellen</span></span>
<span id="cb48-3"><a href="varianzanalyse.html#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Gruppe =</span> <span class="fu">str_c</span>(Schwierigkeitsgrad, Wettkampfpraeferenz, <span class="at">sep =</span> <span class="st">&quot;-&quot;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb48-4"><a href="varianzanalyse.html#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Posthoc-Test durchführen</span></span>
<span id="cb48-5"><a href="varianzanalyse.html#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">games_howell_test</span>(<span class="at">formula =</span> Highscore <span class="sc">~</span> Gruppe) <span class="sc">%&gt;%</span> </span>
<span id="cb48-6"><a href="varianzanalyse.html#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Zur Übersichtlichkeit Zahlenwerte runden</span></span>
<span id="cb48-7"><a href="varianzanalyse.html#cb48-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_at</span>(<span class="fu">c</span>(<span class="st">&quot;estimate&quot;</span>, <span class="st">&quot;conf.low&quot;</span>, <span class="st">&quot;conf.high&quot;</span>), format, <span class="at">digits =</span> <span class="dv">0</span>, <span class="at">nsmall =</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb48-8"><a href="varianzanalyse.html#cb48-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Zur Übersichtlichkeit nur relevante Variablen auswählen</span></span>
<span id="cb48-9"><a href="varianzanalyse.html#cb48-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(group1, group2, estimate, p.adj.signif) <span class="sc">%&gt;%</span> </span>
<span id="cb48-10"><a href="varianzanalyse.html#cb48-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Nur die Mittelwertunterschiede herausfiltern die mich tatsächlich interessieren </span></span>
<span id="cb48-11"><a href="varianzanalyse.html#cb48-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_extract</span>(group1, <span class="st">&quot;^[einfach|mittel|schwer]&quot;</span>) <span class="sc">==</span> <span class="fu">str_extract</span>(group2, <span class="st">&quot;^[einfach|mittel|schwer]&quot;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 3 x 4
##   group1                        group2                     estimate p.adj.signif
##   &lt;chr&gt;                         &lt;chr&gt;                      &lt;chr&gt;    &lt;chr&gt;       
## 1 einfach-geringe Wettkampfprä… einfach-hohe Wettkampfprä… &quot; 1791&quot;  **          
## 2 mittel-geringe Wettkampfpräf… mittel-hohe Wettkampfpräf… &quot; -310&quot;  ns          
## 3 schwer-geringe Wettkampfpräf… schwer-hohe Wettkampfpräf… &quot;  198&quot;  ns</code></pre>
<p>Ich interessiere mich vor allem für die Mittelwertunterschiede innerhalb jedes Schwierigkeitsgerades., deshalb habe ich durch einen Filter, der mit “Regular Expressions” arbeitet hier nur die herausgefiltert. Schaut man sich die Signifikanzniveaus drei Mittelwertunterschiede an, bestätigt sich, was auch schon anhand der Interaktionsgrafik zu vermuten war: Ein Signifikanter Mittelwertunterschied der Wettkampfpräferenz besteht lediglich in der Gruppe “leichter Schwierigkeitsgrad.”</p>
</div>
<div id="abschließende-beurteilung-des-hypothesentests" class="section level3" number="12.4.6">
<h3><span class="header-section-number">12.4.6</span> Abschließende Beurteilung des Hypothesentests</h3>
<p>Alle drei Hypothesen ließen sich mit den Daten bestätigen. Jedoch ist der Haupteffekt des Schwierigkeitsgerades deutlich am größten, während der Haupteffekt der Wettkampfpräferenz gering ausfällt. Es gibt jedoch eine interessante Interaktion zwischen beiden Faktoren, die jedoch lediglich im leichten Schwierigkeitsgrad zum Tragen kommt: Dieser Schwierigkeitsgrad ermöglicht es offenbar den Proband:innen mit einer hohen Wettkampfpräferenz deutlich vor denen, die nur eine niedrig ausgeprägte Wettkampfpräferenz haben, hervorzustechen und einen signifikant höheren Highscore zu erzielen. In schwereren Schwierigkeitsgraden niveliert sich der Einfluss der Wettkampfpräferenz.</p>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>Selbstverständlich ist auch ein höheres Datenniveau möglich. Wegen der Stichprobengröße in den einzelnen Gruppen und der Übersichtlichkeit sollte die unabhängige Variable aber nicht sehr viele Ausprägungen haben, weshalb metrische Variablen kaum als Faktoren in der Varianzanalyse eingesetzt werden.<a href="varianzanalyse.html#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>Die übrigen Voraussetzungen für die Varianzanalyse sind vom Prinzip her ähnlich zum T-Test. Deshalb wird an dieser Stelle nicht erneut darauf eingegangen<a href="varianzanalyse.html#fnref2" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="t-tests.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="literaturverzeichnis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/xvariable/r_book/edit/main/120_anova.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["r_book.pdf"],
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
